#pragma checksum "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\SMS\Views\Engine\ESE_05_00.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "e26681f67e3cb55b04f6666010b6f2b8b120157d"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.Areas_SMS_Views_Engine_ESE_05_00), @"mvc.1.0.view", @"/Areas/SMS/Views/Engine/ESE_05_00.cshtml")]
[assembly:global::Microsoft.AspNetCore.Mvc.Razor.Compilation.RazorViewAttribute(@"/Areas/SMS/Views/Engine/ESE_05_00.cshtml", typeof(AspNetCore.Areas_SMS_Views_Engine_ESE_05_00))]
namespace AspNetCore
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
#line 1 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\SMS\Views\Engine\ESE_05_00.cshtml"
using Microsoft.AspNetCore.Mvc.Localization;

#line default
#line hidden
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"e26681f67e3cb55b04f6666010b6f2b8b120157d", @"/Areas/SMS/Views/Engine/ESE_05_00.cshtml")]
    public class Areas_SMS_Views_Engine_ESE_05_00 : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<dynamic>
    {
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_0 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("src", new global::Microsoft.AspNetCore.Html.HtmlString("~/js/SMS/SMSRecipient.js"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_1 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("class", new global::Microsoft.AspNetCore.Html.HtmlString("selectpicker"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_2 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("data-live-search", new global::Microsoft.AspNetCore.Html.HtmlString("true"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_3 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("id", new global::Microsoft.AspNetCore.Html.HtmlString("cboBusinessLocation"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_4 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("title", new global::Microsoft.AspNetCore.Html.HtmlString("Select"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_5 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("data-size", new global::Microsoft.AspNetCore.Html.HtmlString("8"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_6 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("id", new global::Microsoft.AspNetCore.Html.HtmlString("cboFormId"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_7 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("onchange", new global::Microsoft.AspNetCore.Html.HtmlString("fnOnFormIdChange()"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        #line hidden
        #pragma warning disable 0169
        private string __tagHelperStringValueBuffer;
        #pragma warning restore 0169
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext __tagHelperExecutionContext;
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner __tagHelperRunner = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner();
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __backed__tagHelperScopeManager = null;
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __tagHelperScopeManager
        {
            get
            {
                if (__backed__tagHelperScopeManager == null)
                {
                    __backed__tagHelperScopeManager = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager(StartTagHelperWritingScope, EndTagHelperWritingScope);
                }
                return __backed__tagHelperScopeManager;
            }
        }
        private global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper;
        private global::Microsoft.AspNetCore.Mvc.TagHelpers.SelectTagHelper __Microsoft_AspNetCore_Mvc_TagHelpers_SelectTagHelper;
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            BeginContext(134, 2, true);
            WriteLiteral("\r\n");
            EndContext();
#line 5 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\SMS\Views\Engine\ESE_05_00.cshtml"
  
    ViewData["Title"] = "ESE_05_00";
    Layout = "~/Views/Shared/_Layout.cshtml";

#line default
#line hidden
#line 9 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\SMS\Views\Engine\ESE_05_00.cshtml"
  
    var userFormRole = (eSyaEnterprise_UI.Models.DO_UserFormRole)ViewBag.UserFormRole;

#line default
#line hidden
            BeginContext(323, 46, true);
            WriteLiteral("<script>\r\n    var _userFormRole = JSON.parse(\'");
            EndContext();
            BeginContext(370, 38, false);
#line 13 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\SMS\Views\Engine\ESE_05_00.cshtml"
                               Write(Html.Raw(Json.Serialize(userFormRole)));

#line default
#line hidden
            EndContext();
            BeginContext(408, 50, true);
            WriteLiteral("\');\r\n\r\n    var localization = {\r\n         SMSID: \'");
            EndContext();
            BeginContext(459, 18, false);
#line 16 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\SMS\Views\Engine\ESE_05_00.cshtml"
            Write(Localizer["SMSID"]);

#line default
#line hidden
            EndContext();
            BeginContext(477, 30, true);
            WriteLiteral("\',\r\n         SMSDescription: \'");
            EndContext();
            BeginContext(508, 27, false);
#line 17 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\SMS\Views\Engine\ESE_05_00.cshtml"
                     Write(Localizer["SMSDescription"]);

#line default
#line hidden
            EndContext();
            BeginContext(535, 28, true);
            WriteLiteral("\',\r\n         SMSStatement: \'");
            EndContext();
            BeginContext(564, 25, false);
#line 18 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\SMS\Views\Engine\ESE_05_00.cshtml"
                   Write(Localizer["SMSStatement"]);

#line default
#line hidden
            EndContext();
            BeginContext(589, 22, true);
            WriteLiteral("\',\r\n         Status: \'");
            EndContext();
            BeginContext(612, 19, false);
#line 19 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\SMS\Views\Engine\ESE_05_00.cshtml"
             Write(Localizer["Status"]);

#line default
#line hidden
            EndContext();
            BeginContext(631, 23, true);
            WriteLiteral("\',\r\n         Actions: \'");
            EndContext();
            BeginContext(655, 20, false);
#line 20 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\SMS\Views\Engine\ESE_05_00.cshtml"
              Write(Localizer["Actions"]);

#line default
#line hidden
            EndContext();
            BeginContext(675, 28, true);
            WriteLiteral("\',\r\n         AddRecipient: \'");
            EndContext();
            BeginContext(704, 25, false);
#line 21 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\SMS\Views\Engine\ESE_05_00.cshtml"
                   Write(Localizer["AddRecipient"]);

#line default
#line hidden
            EndContext();
            BeginContext(729, 29, true);
            WriteLiteral("\',\r\n         EditRecipient: \'");
            EndContext();
            BeginContext(759, 26, false);
#line 22 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\SMS\Views\Engine\ESE_05_00.cshtml"
                    Write(Localizer["EditRecipient"]);

#line default
#line hidden
            EndContext();
            BeginContext(785, 29, true);
            WriteLiteral("\',\r\n         ViewRecipient: \'");
            EndContext();
            BeginContext(815, 26, false);
#line 23 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\SMS\Views\Engine\ESE_05_00.cshtml"
                    Write(Localizer["ViewRecipient"]);

#line default
#line hidden
            EndContext();
            BeginContext(841, 22, true);
            WriteLiteral("\',\r\n         Delete: \'");
            EndContext();
            BeginContext(864, 19, false);
#line 24 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\SMS\Views\Engine\ESE_05_00.cshtml"
             Write(Localizer["Delete"]);

#line default
#line hidden
            EndContext();
            BeginContext(883, 26, true);
            WriteLiteral("\',\r\n         DeActivate: \'");
            EndContext();
            BeginContext(910, 23, false);
#line 25 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\SMS\Views\Engine\ESE_05_00.cshtml"
                 Write(Localizer["DeActivate"]);

#line default
#line hidden
            EndContext();
            BeginContext(933, 24, true);
            WriteLiteral("\',\r\n         Activate: \'");
            EndContext();
            BeginContext(958, 21, false);
#line 26 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\SMS\Views\Engine\ESE_05_00.cshtml"
               Write(Localizer["Activate"]);

#line default
#line hidden
            EndContext();
            BeginContext(979, 22, true);
            WriteLiteral("\',\r\n         Active: \'");
            EndContext();
            BeginContext(1002, 19, false);
#line 27 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\SMS\Views\Engine\ESE_05_00.cshtml"
             Write(Localizer["Active"]);

#line default
#line hidden
            EndContext();
            BeginContext(1021, 23, true);
            WriteLiteral("\',\r\n         Actions: \'");
            EndContext();
            BeginContext(1045, 20, false);
#line 28 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\SMS\Views\Engine\ESE_05_00.cshtml"
              Write(Localizer["Actions"]);

#line default
#line hidden
            EndContext();
            BeginContext(1065, 20, true);
            WriteLiteral("\',\r\n         Edit: \'");
            EndContext();
            BeginContext(1086, 17, false);
#line 29 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\SMS\Views\Engine\ESE_05_00.cshtml"
           Write(Localizer["Edit"]);

#line default
#line hidden
            EndContext();
            BeginContext(1103, 20, true);
            WriteLiteral("\',\r\n         View: \'");
            EndContext();
            BeginContext(1124, 17, false);
#line 30 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\SMS\Views\Engine\ESE_05_00.cshtml"
           Write(Localizer["View"]);

#line default
#line hidden
            EndContext();
            BeginContext(1141, 20, true);
            WriteLiteral("\',\r\n         Save: \'");
            EndContext();
            BeginContext(1162, 17, false);
#line 31 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\SMS\Views\Engine\ESE_05_00.cshtml"
           Write(Localizer["Save"]);

#line default
#line hidden
            EndContext();
            BeginContext(1179, 22, true);
            WriteLiteral("\',\r\n         Cancel: \'");
            EndContext();
            BeginContext(1202, 19, false);
#line 32 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\SMS\Views\Engine\ESE_05_00.cshtml"
             Write(Localizer["Cancel"]);

#line default
#line hidden
            EndContext();
            BeginContext(1221, 25, true);
            WriteLiteral("\',\r\n\r\n    };\r\n</script>\r\n");
            EndContext();
            DefineSection("scripts", async() => {
                BeginContext(1263, 6, true);
                WriteLiteral("\r\n    ");
                EndContext();
                BeginContext(1269, 48, false);
                __tagHelperExecutionContext = __tagHelperScopeManager.Begin("script", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "e26681f67e3cb55b04f6666010b6f2b8b120157d14003", async() => {
                }
                );
                __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper>();
                __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_0);
                await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
                if (!__tagHelperExecutionContext.Output.IsContentModified)
                {
                    await __tagHelperExecutionContext.SetOutputContentAsync();
                }
                Write(__tagHelperExecutionContext.Output);
                __tagHelperExecutionContext = __tagHelperScopeManager.End();
                EndContext();
                BeginContext(1317, 2, true);
                WriteLiteral("\r\n");
                EndContext();
            }
            );
            BeginContext(1322, 120, true);
            WriteLiteral("\r\n<div class=\"row\">\r\n    <div class=\"col-lg-3 col-md-3 col-sm-4\">\r\n        <div class=\"form-group\">\r\n            <label>");
            EndContext();
            BeginContext(1443, 29, false);
#line 43 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\SMS\Views\Engine\ESE_05_00.cshtml"
              Write(Localizer["BusinessLocation"]);

#line default
#line hidden
            EndContext();
            BeginContext(1472, 23, true);
            WriteLiteral(" </label>\r\n            ");
            EndContext();
            BeginContext(1495, 179, false);
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("select", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "e26681f67e3cb55b04f6666010b6f2b8b120157d15915", async() => {
            }
            );
            __Microsoft_AspNetCore_Mvc_TagHelpers_SelectTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.SelectTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_SelectTagHelper);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_1);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_2);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_3);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_4);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_5);
#line 45 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\SMS\Views\Engine\ESE_05_00.cshtml"
__Microsoft_AspNetCore_Mvc_TagHelpers_SelectTagHelper.Items = ViewBag.BusinessLocationList;

#line default
#line hidden
            __tagHelperExecutionContext.AddTagHelperAttribute("asp-items", __Microsoft_AspNetCore_Mvc_TagHelpers_SelectTagHelper.Items, global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            EndContext();
            BeginContext(1674, 129, true);
            WriteLiteral("\r\n        </div>\r\n    </div>\r\n    <div class=\"col-lg-3 col-md-3 col-sm-4\">\r\n        <div class=\"form-group\">\r\n            <label>");
            EndContext();
            BeginContext(1804, 21, false);
#line 50 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\SMS\Views\Engine\ESE_05_00.cshtml"
              Write(Localizer["FormName"]);

#line default
#line hidden
            EndContext();
            BeginContext(1825, 23, true);
            WriteLiteral(" </label>\r\n            ");
            EndContext();
            BeginContext(1848, 187, false);
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("select", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "e26681f67e3cb55b04f6666010b6f2b8b120157d18387", async() => {
            }
            );
            __Microsoft_AspNetCore_Mvc_TagHelpers_SelectTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.SelectTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_SelectTagHelper);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_1);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_2);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_6);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_4);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_5);
#line 52 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\SMS\Views\Engine\ESE_05_00.cshtml"
__Microsoft_AspNetCore_Mvc_TagHelpers_SelectTagHelper.Items = ViewBag.FormList;

#line default
#line hidden
            __tagHelperExecutionContext.AddTagHelperAttribute("asp-items", __Microsoft_AspNetCore_Mvc_TagHelpers_SelectTagHelper.Items, global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_7);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            EndContext();
            BeginContext(2035, 629, true);
            WriteLiteral(@"
        </div>
    </div>
    <div class=""col-lg-12 col-md-12 col-sm-12 padbot10"">
        <table id=""jqgSMSToWhom""></table>
        <div id=""jqpSMSToWhom""></div>
    </div>
</div>
<div class=""modal fullscreen fade in"" id=""PopupSMSToWhom"" data-keyboard=""false"" data-backdrop=""static"">
    <div class=""modal-dialog modal-lg  "" role=""document"" style=""box-shadow:none;"">
        <div class=""modal-content "">
            <div class=""modal-header popupHeader"">
                <button type=""button"" class=""close ml-auto"" data-dismiss=""modal""> <i class=""fa fa-times""></i></button>
                <h4 class=""modal-title"">");
            EndContext();
            BeginContext(2665, 25, false);
#line 65 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\SMS\Views\Engine\ESE_05_00.cshtml"
                                   Write(Localizer["AddRecipient"]);

#line default
#line hidden
            EndContext();
            BeginContext(2690, 481, true);
            WriteLiteral(@" </h4>
            </div>
            <div class=""modal-body"">
                <div class=""row"">
                    <div class=""col-sm-12"">
                        <input type=""text"" class=""form-control"" id="""" style=""display:none"">
                    </div>
                </div>
                <div class=""row padbot4"">
                    <div class=""col-lg-4 col-md-4 col-sm-6"">
                        <div class=""form-group"">
                            <label>");
            EndContext();
            BeginContext(3172, 27, false);
#line 76 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\SMS\Views\Engine\ESE_05_00.cshtml"
                              Write(Localizer["SMSDescription"]);

#line default
#line hidden
            EndContext();
            BeginContext(3199, 765, true);
            WriteLiteral(@" </label>
                            <select class=""selectpicker form-control"" title=""Select"" data-live-search=""true"" id=""cboSMSDescription"" onchange=""fnGridLoadSMSRecipient()""></select>
                        </div>
                    </div>
                    <div class=""col-lg-12 col-md-12 col-sm-12 form-group"">
                        <table id=""jqgSMSRecipient""></table>
                        <div id=""jqpSMSRecipient""></div>
                    </div>

                </div>
                <section class=""bg-white"">
                    <div class=""row"">
                        <div class=""col-lg-6 col-md-6 col-sm-6"">
                            <div class=""form-group"">
                                <label for=""txtRecipientName"">");
            EndContext();
            BeginContext(3965, 26, false);
#line 90 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\SMS\Views\Engine\ESE_05_00.cshtml"
                                                         Write(Localizer["RecipientName"]);

#line default
#line hidden
            EndContext();
            BeginContext(3991, 373, true);
            WriteLiteral(@" </label>
                                <input id=""txtRecipientName"" class=""form-control"" maxlength=""50"" type=""text"" />
                            </div>
                        </div>
                        <div class=""col-lg-2 col-md-6 col-sm-6"">
                            <div class=""form-group"">
                                <label for=""txtMobileNumber"">");
            EndContext();
            BeginContext(4365, 25, false);
#line 96 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\SMS\Views\Engine\ESE_05_00.cshtml"
                                                        Write(Localizer["MobileNumber"]);

#line default
#line hidden
            EndContext();
            BeginContext(4390, 367, true);
            WriteLiteral(@" </label>
                                <input id=""txtMobileNumber"" class=""form-control"" maxlength=""20"" type=""text"" />
                            </div>
                        </div>
                        <div class=""col-lg-6 col-md-6 col-sm-6"">
                            <div class=""form-group"">
                                <label for=""txtRemarks"">");
            EndContext();
            BeginContext(4758, 20, false);
#line 102 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\SMS\Views\Engine\ESE_05_00.cshtml"
                                                   Write(Localizer["Remarks"]);

#line default
#line hidden
            EndContext();
            BeginContext(4778, 722, true);
            WriteLiteral(@" </label>
                                <input id=""txtRemarks"" class=""form-control"" maxlength=""25"" type=""text"" />
                            </div>
                        </div>
                        <div class=""col-lg-2  col-md-3 col-sm-12 col-xs-12"">
                            <div class=""form-group"">
                                <div class=""default-checkbox padbot15"">
                                    <label class=""mdl-checkbox mdl-js-checkbox mdl-js-ripple-effect"" for=""chkActiveStatus"">
                                        <input type=""checkbox"" id=""chkActiveStatus"" checked=""checked"" class=""mdl-checkbox__input"">
                                        <span class=""mdl-checkbox__label"">");
            EndContext();
            BeginContext(5501, 25, false);
#line 111 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\SMS\Views\Engine\ESE_05_00.cshtml"
                                                                     Write(Localizer["ActiveStatus"]);

#line default
#line hidden
            EndContext();
            BeginContext(5526, 609, true);
            WriteLiteral(@" </span>
                                    </label>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
            <div class=""modal-footer"">
                <div class=""row"">
                    <div class=""col-lg-12"">
                        <button class=""mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent primary-button"" id=""btnSaveRecipient"" onclick=""fnSaveSMSRecipient();"">
                            <i class=""fa fa-save""></i>");
            EndContext();
            BeginContext(6136, 17, false);
#line 123 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\SMS\Views\Engine\ESE_05_00.cshtml"
                                                 Write(Localizer["Save"]);

#line default
#line hidden
            EndContext();
            BeginContext(6153, 269, true);
            WriteLiteral(@"
                        </button>
                        <button class=""mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect  cancel-button cancel-button"" data-dismiss=""modal"" id=""btnCancelRecipient"" onclick=""fnClearFields()""><i class=""fa fa-times""></i>");
            EndContext();
            BeginContext(6423, 19, false);
#line 125 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\SMS\Views\Engine\ESE_05_00.cshtml"
                                                                                                                                                                                                                                   Write(Localizer["Cancel"]);

#line default
#line hidden
            EndContext();
            BeginContext(6442, 122, true);
            WriteLiteral(" </button>\r\n                    </div>\r\n                </div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n\r\n");
            EndContext();
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public IViewLocalizer Localizer { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<dynamic> Html { get; private set; }
    }
}
#pragma warning restore 1591
