#pragma checksum "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\eSyaConfig\Views\BusinessStructure\V_103_00.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "812b87c9646ff014a0483ea6b4a6bb657bc8e35f"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.Areas_eSyaConfig_Views_BusinessStructure_V_103_00), @"mvc.1.0.view", @"/Areas/eSyaConfig/Views/BusinessStructure/V_103_00.cshtml")]
[assembly:global::Microsoft.AspNetCore.Mvc.Razor.Compilation.RazorViewAttribute(@"/Areas/eSyaConfig/Views/BusinessStructure/V_103_00.cshtml", typeof(AspNetCore.Areas_eSyaConfig_Views_BusinessStructure_V_103_00))]
namespace AspNetCore
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
#line 1 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\eSyaConfig\Views\BusinessStructure\V_103_00.cshtml"
using Microsoft.AspNetCore.Mvc.Localization;

#line default
#line hidden
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"812b87c9646ff014a0483ea6b4a6bb657bc8e35f", @"/Areas/eSyaConfig/Views/BusinessStructure/V_103_00.cshtml")]
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"23ac09be4bcfaa7f9829a01d1a134874eaae1f3b", @"/Areas/eSyaConfig/Views/_ViewImports.cshtml")]
    public class Areas_eSyaConfig_Views_BusinessStructure_V_103_00 : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<dynamic>
    {
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_0 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("href", new global::Microsoft.AspNetCore.Html.HtmlString("~/css/jsTree.css"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_1 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("rel", new global::Microsoft.AspNetCore.Html.HtmlString("stylesheet"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_2 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("src", new global::Microsoft.AspNetCore.Html.HtmlString("~/js/jsTree.js"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_3 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("value", "0", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_4 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("value", "P", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_5 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("value", "S", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        #line hidden
        #pragma warning disable 0169
        private string __tagHelperStringValueBuffer;
        #pragma warning restore 0169
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext __tagHelperExecutionContext;
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner __tagHelperRunner = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner();
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __backed__tagHelperScopeManager = null;
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __tagHelperScopeManager
        {
            get
            {
                if (__backed__tagHelperScopeManager == null)
                {
                    __backed__tagHelperScopeManager = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager(StartTagHelperWritingScope, EndTagHelperWritingScope);
                }
                return __backed__tagHelperScopeManager;
            }
        }
        private global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper;
        private global::Microsoft.AspNetCore.Mvc.TagHelpers.OptionTagHelper __Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper;
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            BeginContext(46, 2, true);
            WriteLiteral("\r\n");
            EndContext();
#line 4 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\eSyaConfig\Views\BusinessStructure\V_103_00.cshtml"
  
    ViewData["Title"] = "Business Location";
    Layout = "~/Views/Shared/_Layout.cshtml";

#line default
#line hidden
#line 8 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\eSyaConfig\Views\BusinessStructure\V_103_00.cshtml"
  
    var userFormRole = (eSyaEnterprise_UI.Models.DO_UserFormRole)ViewBag.UserFormRole;

#line default
#line hidden
            BeginContext(277, 46, true);
            WriteLiteral("<script>\r\n    var _userFormRole = JSON.parse(\'");
            EndContext();
            BeginContext(324, 38, false);
#line 12 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\eSyaConfig\Views\BusinessStructure\V_103_00.cshtml"
                               Write(Html.Raw(Json.Serialize(userFormRole)));

#line default
#line hidden
            EndContext();
            BeginContext(362, 63, true);
            WriteLiteral("\');\r\n\r\n    var localization = {\r\n        AddBusinessLocation: \'");
            EndContext();
            BeginContext(426, 32, false);
#line 15 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\eSyaConfig\Views\BusinessStructure\V_103_00.cshtml"
                         Write(Localizer["AddBusinessLocation"]);

#line default
#line hidden
            EndContext();
            BeginContext(458, 31, true);
            WriteLiteral("\',\r\n        BusinessLocation: \'");
            EndContext();
            BeginContext(490, 29, false);
#line 16 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\eSyaConfig\Views\BusinessStructure\V_103_00.cshtml"
                      Write(Localizer["BusinessLocation"]);

#line default
#line hidden
            EndContext();
            BeginContext(519, 35, true);
            WriteLiteral("\',\r\n        EditBusinessLocation: \'");
            EndContext();
            BeginContext(555, 33, false);
#line 17 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\eSyaConfig\Views\BusinessStructure\V_103_00.cshtml"
                          Write(Localizer["EditBusinessLocation"]);

#line default
#line hidden
            EndContext();
            BeginContext(588, 35, true);
            WriteLiteral("\',\r\n        ViewBusinessLocation: \'");
            EndContext();
            BeginContext(624, 33, false);
#line 18 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\eSyaConfig\Views\BusinessStructure\V_103_00.cshtml"
                          Write(Localizer["ViewBusinessLocation"]);

#line default
#line hidden
            EndContext();
            BeginContext(657, 19, true);
            WriteLiteral("\',\r\n        Save: \'");
            EndContext();
            BeginContext(677, 17, false);
#line 19 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\eSyaConfig\Views\BusinessStructure\V_103_00.cshtml"
          Write(Localizer["Save"]);

#line default
#line hidden
            EndContext();
            BeginContext(694, 21, true);
            WriteLiteral("\',\r\n        Update: \'");
            EndContext();
            BeginContext(716, 19, false);
#line 20 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\eSyaConfig\Views\BusinessStructure\V_103_00.cshtml"
            Write(Localizer["Update"]);

#line default
#line hidden
            EndContext();
            BeginContext(735, 23, true);
            WriteLiteral("\',\r\n        Currency: \'");
            EndContext();
            BeginContext(759, 21, false);
#line 21 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\eSyaConfig\Views\BusinessStructure\V_103_00.cshtml"
              Write(Localizer["Currency"]);

#line default
#line hidden
            EndContext();
            BeginContext(780, 21, true);
            WriteLiteral("\',\r\n        Status: \'");
            EndContext();
            BeginContext(802, 19, false);
#line 22 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\eSyaConfig\Views\BusinessStructure\V_103_00.cshtml"
            Write(Localizer["Status"]);

#line default
#line hidden
            EndContext();
            BeginContext(821, 137, true);
            WriteLiteral("\',\r\n    };\r\n</script>\r\n<style>\r\n    .BSCurrencyContainer [class*=\"ui-jqgrid\"]{\r\n        width: 100% !important;\r\n    }\r\n   \r\n</style>\r\n\r\n");
            EndContext();
            BeginContext(958, 49, false);
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("link", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.SelfClosing, "812b87c9646ff014a0483ea6b4a6bb657bc8e35f10094", async() => {
            }
            );
            __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_0);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_1);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            EndContext();
            BeginContext(1007, 2, true);
            WriteLiteral("\r\n");
            EndContext();
            DefineSection("scripts", async() => {
                BeginContext(1026, 6, true);
                WriteLiteral("\r\n    ");
                EndContext();
                BeginContext(1032, 38, false);
                __tagHelperExecutionContext = __tagHelperScopeManager.Begin("script", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "812b87c9646ff014a0483ea6b4a6bb657bc8e35f11528", async() => {
                }
                );
                __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper>();
                __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_2);
                await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
                if (!__tagHelperExecutionContext.Output.IsContentModified)
                {
                    await __tagHelperExecutionContext.SetOutputContentAsync();
                }
                Write(__tagHelperExecutionContext.Output);
                __tagHelperExecutionContext = __tagHelperScopeManager.End();
                EndContext();
                BeginContext(1070, 2, true);
                WriteLiteral("\r\n");
                EndContext();
            }
            );
            BeginContext(1075, 2124, true);
            WriteLiteral(@"<div class=""row"">
    <div class=""col-lg-4 col-md-4 col-sm-6"" id=""divJstBusinessLocation"">
        <div id=""jstBusinessLocation""></div>
    </div>
    <div class=""col-lg-6 col-md-6 col-sm-6"">
        <div class=""demo-card-square mdl-card mdl-shadow--2dp"" id=""pnlMainMenu"" style=""width: 100%; display:none"">
            <div id=""pnlMainModuleHeading"" class=""mdl-card__title mdl-card--expand padleft0 padtop0 h-60 d-block"">
                <h5 class=""mdl-card__title-text"">Add Business Location</h5>
            </div>
            <div class=""mdl-card__supporting-text fullwidth pad0"">

                <div class=""row padbot4 mar0"">
                    <div class=""col-lg-12 col-md-12 col-sm-12"">
                        <div class=""form-group collapse"">
                            <label for=""txtBusinessEntityId"">Busienss Entity Id</label>
                            <input id=""txtBusinessEntityId"" class=""form-control"" maxlength=""10"" type=""text"" data-inputmask=""'mask': '9', 'repeat': 10, 'greedy' : false");
            WriteLiteral(@""" />
                        </div>
                    </div>
                    <div class=""col-lg-12 col-md-12 col-sm-12"">
                        <div class=""form-group collapse"">
                            <label for=""txtBusinessSegmentId"">Segment Id</label>
                            <input id=""txtBusinessSegmentId"" class=""form-control"" maxlength=""10"" type=""text"" data-inputmask=""'mask': '9', 'repeat': 10, 'greedy' : false"" />
                        </div>
                    </div>
                    <div class=""col-lg-12 col-md-12 col-sm-12"">
                        <div class=""form-group collapse"">
                            <label for=""txtBusinessLocationId"">Location Id</label>
                            <input id=""txtBusinessLocationId"" class=""form-control"" maxlength=""10"" type=""text"" data-inputmask=""'mask': '9', 'repeat': 10, 'greedy' : false"" />
                        </div>
                    </div>
                    <div class=""col-lg-12 col-md-12 col-sm-12"">
          ");
            WriteLiteral("              <div class=\"form-group\">\r\n                            <label> ");
            EndContext();
            BeginContext(3200, 25, false);
#line 68 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\eSyaConfig\Views\BusinessStructure\V_103_00.cshtml"
                               Write(Localizer["LocationCode"]);

#line default
#line hidden
            EndContext();
            BeginContext(3225, 329, true);
            WriteLiteral(@" </label>
                            <input id=""txtLocationcode"" class=""form-control"" maxlength=""6"" type=""text"" />
                        </div>
                    </div>
                    <div class=""col-lg-12 col-md-12 col-sm-12"">
                        <div class=""form-group"">
                            <label> ");
            EndContext();
            BeginContext(3555, 32, false);
#line 74 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\eSyaConfig\Views\BusinessStructure\V_103_00.cshtml"
                               Write(Localizer["LocationDescription"]);

#line default
#line hidden
            EndContext();
            BeginContext(3587, 338, true);
            WriteLiteral(@" </label>
                            <input id=""txtLocationDescription"" class=""form-control"" maxlength=""100"" type=""text"" />
                        </div>
                    </div>
                    <div class=""col-lg-12 col-md-12 col-sm-12"">
                        <div class=""form-group"">
                            <label> ");
            EndContext();
            BeginContext(3926, 25, false);
#line 80 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\eSyaConfig\Views\BusinessStructure\V_103_00.cshtml"
                               Write(Localizer["BusinessName"]);

#line default
#line hidden
            EndContext();
            BeginContext(3951, 369, true);
            WriteLiteral(@" </label>
                            <input id=""txtBusinessName"" class=""form-control"" maxlength=""100"" type=""text"" />
                        </div>
                    </div>


                    <div id=""dvTaxIdentification"" class=""col-lg-6  col-md-6 col-sm-12 col-xs-12"">
                        <div class=""form-group"">
                            <label> ");
            EndContext();
            BeginContext(4321, 30, false);
#line 88 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\eSyaConfig\Views\BusinessStructure\V_103_00.cshtml"
                               Write(Localizer["TaxIdentification"]);

#line default
#line hidden
            EndContext();
            BeginContext(4351, 224, true);
            WriteLiteral(" </label>\r\n                            <div>\r\n                                <select class=\"selectpicker\" data-live-search=\"true\" id=\"cboTaxIdentification\" title=\"Select\" data-size=\"8\">\r\n                                    ");
            EndContext();
            BeginContext(4575, 33, false);
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("option", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "812b87c9646ff014a0483ea6b4a6bb657bc8e35f18127", async() => {
                BeginContext(4593, 6, true);
                WriteLiteral("Select");
                EndContext();
            }
            );
            __Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.OptionTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper);
            __Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper.Value = (string)__tagHelperAttribute_3.Value;
            __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_3);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            EndContext();
            BeginContext(4608, 301, true);
            WriteLiteral(@"
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class=""col-lg-6  col-md-6 col-sm-12 col-xs-12"">
                        <div class=""form-group"">
                            <label> ");
            EndContext();
            BeginContext(4910, 24, false);
#line 98 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\eSyaConfig\Views\BusinessStructure\V_103_00.cshtml"
                               Write(Localizer["LicenseType"]);

#line default
#line hidden
            EndContext();
            BeginContext(4934, 205, true);
            WriteLiteral(" </label>\r\n                            <div>\r\n                                <select class=\"selectpicker\" data-live-search=\"false\" id=\"cboLicenseType\" title=\"Select\">\r\n                                    ");
            EndContext();
            BeginContext(5139, 33, false);
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("option", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "812b87c9646ff014a0483ea6b4a6bb657bc8e35f20432", async() => {
                BeginContext(5157, 6, true);
                WriteLiteral("Select");
                EndContext();
            }
            );
            __Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.OptionTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper);
            __Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper.Value = (string)__tagHelperAttribute_3.Value;
            __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_3);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            EndContext();
            BeginContext(5172, 38, true);
            WriteLiteral("\r\n                                    ");
            EndContext();
            BeginContext(5210, 36, false);
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("option", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "812b87c9646ff014a0483ea6b4a6bb657bc8e35f21846", async() => {
                BeginContext(5228, 9, true);
                WriteLiteral("Perpetual");
                EndContext();
            }
            );
            __Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.OptionTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper);
            __Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper.Value = (string)__tagHelperAttribute_4.Value;
            __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_4);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            EndContext();
            BeginContext(5246, 38, true);
            WriteLiteral("\r\n                                    ");
            EndContext();
            BeginContext(5284, 39, false);
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("option", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "812b87c9646ff014a0483ea6b4a6bb657bc8e35f23263", async() => {
                BeginContext(5302, 12, true);
                WriteLiteral("Subscription");
                EndContext();
            }
            );
            __Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.OptionTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper);
            __Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper.Value = (string)__tagHelperAttribute_5.Value;
            __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_5);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            EndContext();
            BeginContext(5323, 311, true);
            WriteLiteral(@"
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class=""col-lg-6  col-md-4 col-sm-12 col-xs-12"">
                        <div class=""form-group lbl-right"">
                            <label> ");
            EndContext();
            BeginContext(5635, 25, false);
#line 110 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\eSyaConfig\Views\BusinessStructure\V_103_00.cshtml"
                               Write(Localizer["UserLicenses"]);

#line default
#line hidden
            EndContext();
            BeginContext(5660, 383, true);
            WriteLiteral(@" </label>
                            <input type=""text"" id=""txtUserLicenses"" name=""name"" value="""" class=""form-control integerFormat"" maxlength=""5"" />
                        </div>
                    </div>
                    <div class=""col-lg-6  col-md-4 col-sm-12 col-xs-12"">
                        <div class=""form-group lbl-right"">
                            <label> ");
            EndContext();
            BeginContext(6044, 31, false);
#line 116 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\eSyaConfig\Views\BusinessStructure\V_103_00.cshtml"
                               Write(Localizer["LicensesToNoOfBeds"]);

#line default
#line hidden
            EndContext();
            BeginContext(6075, 758, true);
            WriteLiteral(@" </label>
                            <input type=""text"" id=""txtNoOfBeds"" name=""name"" value="""" class=""form-control integerFormat"" maxlength=""5"" />
                        </div>
                    </div>
                </div>

                <div class=""row padbot4 mar0"">
                    <div class=""col-lg-3  col-md-6 col-sm-12 col-xs-12"">
                        <div class=""default-checkbox checkbox-group"">
                            <label class=""mdl-checkbox mdl-js-checkbox mdl-js-ripple-effect"" for=""chkToLocalCurrency"">
                                <input type=""checkbox"" id=""chkToLocalCurrency"" class=""mdl-checkbox__input"" onchange=""fnToLocalCurrency(this)"">
                                <span class=""mdl-checkbox__label"">");
            EndContext();
            BeginContext(6834, 28, false);
#line 127 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\eSyaConfig\Views\BusinessStructure\V_103_00.cshtml"
                                                             Write(Localizer["ToLocalCurrency"]);

#line default
#line hidden
            EndContext();
            BeginContext(6862, 580, true);
            WriteLiteral(@"</span>
                            </label>
                        </div>
                    </div>
                    <div class=""col-lg-3  col-md-3 col-sm-12 col-xs-12 "">
                        <div class=""default-checkbox checkbox-group"">
                            <label class=""mdl-checkbox mdl-js-checkbox mdl-js-ripple-effect"" for=""chkToCurrCurrency"">
                                <input type=""checkbox"" id=""chkToCurrCurrency"" class=""mdl-checkbox__input"" onchange=""fnToCurrCurrency(this)"">
                                <span class=""mdl-checkbox__label"">");
            EndContext();
            BeginContext(7443, 29, false);
#line 135 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\eSyaConfig\Views\BusinessStructure\V_103_00.cshtml"
                                                             Write(Localizer["ToCurrConversion"]);

#line default
#line hidden
            EndContext();
            BeginContext(7472, 581, true);
            WriteLiteral(@"</span>
                            </label>
                        </div>
                    </div>

                    <div class=""col-lg-3  col-md-6 col-sm-12 col-xs-12"">
                        <div class=""default-checkbox checkbox-group"">
                            <label class=""mdl-checkbox mdl-js-checkbox mdl-js-ripple-effect"" for=""chkToRealCurrency"">
                                <input type=""checkbox"" id=""chkToRealCurrency"" class=""mdl-checkbox__input"" onchange=""fnToRealCurrency(this)"">
                                <span class=""mdl-checkbox__label"">");
            EndContext();
            BeginContext(8054, 27, false);
#line 144 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\eSyaConfig\Views\BusinessStructure\V_103_00.cshtml"
                                                             Write(Localizer["ToRealCurrency"]);

#line default
#line hidden
            EndContext();
            BeginContext(8081, 543, true);
            WriteLiteral(@"</span>
                            </label>
                        </div>
                    </div>

                    <div class=""col-lg-3  col-md-6 col-sm-12 col-xs-12"">
                        <div class=""default-checkbox checkbox-group"">
                            <label class=""mdl-checkbox mdl-js-checkbox mdl-js-ripple-effect"" for=""chkActiveStatus"">
                                <input type=""checkbox"" id=""chkActiveStatus"" class=""mdl-checkbox__input"">
                                <span class=""mdl-checkbox__label"">");
            EndContext();
            BeginContext(8625, 19, false);
#line 153 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\eSyaConfig\Views\BusinessStructure\V_103_00.cshtml"
                                                             Write(Localizer["Active"]);

#line default
#line hidden
            EndContext();
            BeginContext(8644, 528, true);
            WriteLiteral(@"</span>
                            </label>
                        </div>
                    </div>

                    <div class=""col-lg-12 col-md-12 col-sm-12 padbot10"">
                        <div class=""BSCurrencyContainer"">
                            <table id=""jqgBSCurrency""></table>
                            <div id=""jqpBSCurrency""></div>
                        </div>
                    </div>

                    <div class=""col-sm-12 col-md-12 col-lg-12 form-group"">
                        ");
            EndContext();
            BeginContext(9173, 73, false);
#line 166 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\eSyaConfig\Views\BusinessStructure\V_103_00.cshtml"
                   Write(await Component.InvokeAsync("eSyaParameter", new { parameterType = "2" }));

#line default
#line hidden
            EndContext();
            BeginContext(9246, 344, true);
            WriteLiteral(@"

                    </div>
                </div>
            </div>

            <div class=""mdl-card__actions mdl-card--border"" style=""text-align: center;"">
                <button class=""mdl-button mdl-js-button mdl-button--raised primary-button"" id=""btnAddBusinessLocation"" onclick=""fnSaveBusinessLocation()"">
                    ");
            EndContext();
            BeginContext(9591, 17, false);
#line 174 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\eSyaConfig\Views\BusinessStructure\V_103_00.cshtml"
               Write(Localizer["Save"]);

#line default
#line hidden
            EndContext();
            BeginContext(9608, 462, true);
            WriteLiteral(@"
                </button>

            </div>

        </div>

    </div>
    <div class=""col-lg-2 col-md-2 col-sm-6"">
        <div>
            <h5>Action</h5>
        </div>
        <div class=""row"">
            <div class=""col-lg-12 btn_pdnTop"">
                <button class=""mdl-button mdl-js-button mdl-button--raised cancel-button btn_wdth"" id=""btnDeleteNode"" onclick=""fnDeleteNode()"">
                    <i class=""fa fa-times""></i>      ");
            EndContext();
            BeginContext(10071, 23, false);
#line 189 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\eSyaConfig\Views\BusinessStructure\V_103_00.cshtml"
                                                Write(Localizer["DeleteNode"]);

#line default
#line hidden
            EndContext();
            BeginContext(10094, 295, true);
            WriteLiteral(@"
                </button>
            </div>

            <div class=""col-lg-12 btn_pdnTop"">
                <button class=""mdl-button mdl-js-button mdl-button--raised primary-button btn_wdth"" id=""btnExpandAll"" onclick=""fnExpandAll()"">
                    <i class=""fas fa-expand""></i>   ");
            EndContext();
            BeginContext(10390, 22, false);
#line 195 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\eSyaConfig\Views\BusinessStructure\V_103_00.cshtml"
                                               Write(Localizer["ExpandAll"]);

#line default
#line hidden
            EndContext();
            BeginContext(10412, 299, true);
            WriteLiteral(@"
                </button>
            </div>
            <div class=""col-lg-12 btn_pdnTop"">
                <button class=""mdl-button mdl-js-button mdl-button--raised primary-button btn_wdth"" id=""btnCollapseAll"" onclick=""fnCollapseAll()"">
                    <i class=""fas fa-compress""></i>   ");
            EndContext();
            BeginContext(10712, 24, false);
#line 200 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\eSyaConfig\Views\BusinessStructure\V_103_00.cshtml"
                                                 Write(Localizer["CollapseAll"]);

#line default
#line hidden
            EndContext();
            BeginContext(10736, 25156, true);
            WriteLiteral(@"
                </button>
            </div>

        </div>
    </div>
</div>


<script>
    var NodeID;
    var prevSelectedID;
    var TaxId;
    $(document).ready(function () {
        $(""#pnlMainMenu"").hide();
        LoadBusinessLocationTree();
        $(""#btnDeleteNode"").attr(""disabled"", _userFormRole.IsDelete === false);
    });

    function LoadBusinessLocationTree() {
        $.ajax({
            url: getBaseURL() + '/BusinessStructure/GetBusinessLocationforTreeView',
            success: function (result) {
                fnGetBusinessLocation_Success(result);
            },
            error: function (error) {
                toastr.error(error.status);
            }
        });
    }

    var editRow = false;
    function fnGetBusinessLocation_Success(dataArray) {
        $(""#jstBusinessLocation"").jstree({
            ""state"": { ""checkbox_disabled"": true },
            ""checkbox"": {
                ""keep_selected_style"": false
            },
            c");
            WriteLiteral(@"ore: { 'data': dataArray, 'check_callback': true, 'multiple': true }

        });

        $(""#jstBusinessLocation"").on('loaded.jstree', function () {

            $(""#jstBusinessLocation"").jstree('open_all');
            $(""#jstBusinessLocation"").jstree()._open_to(prevSelectedID);
            $('#jstBusinessLocation').jstree().select_node(prevSelectedID);

        });

        $('#jstBusinessLocation').on(""changed.jstree"", function (e, data) {

            if (data.node != undefined) {
                if (prevSelectedID != data.node.id) {
                    prevSelectedID = data.node.id;

                    if (data.node.id == ""0"") {
                        fnClearFields();
                        $(""#pnlMainMenu"").hide();
                    }
                    else {
                        TaxId = 0;
                        $('#View').remove();
                        $('#Edit').remove();
                        $('#Add').remove();

                        $(""#pnlMainMenu"")");
            WriteLiteral(@".hide();

                        if (data.node.parent == ""MM"") {
                            fnClearFields();
                            $(""#pnlMainMenu"").hide();
                        }
                        else if (data.node.id.startsWith(""SM"")) {
                            $('#' + data.node.id + ""_anchor"").html($('#' + data.node.id + ""_anchor"").html() + '<span id=""Add"" style=""padding-left:10px;padding-right:10px"">&nbsp;<i class=""fa fa-plus"" style=""color:#337ab7""aria-hidden=""true""></i></span>')
                            
                            $('#Add').on('click', function () {
                                if (_userFormRole.IsInsert === false) {
                                    $('#pnlMainMenu').hide();
                                    toastr.warning(errorMsgCS[""E003""]);
                                    return;
                                }

                                var IsMultiLocation = true;
                                $.ajax({
                 ");
            WriteLiteral(@"                   url: getBaseURL() + '/BusinessStructure/IsAllowMultiLocation?BusinessId=' + data.node.id.substring(2).split(""_"")[0] + ""&SegmentId="" + data.node.id.substring(2).split(""_"")[1],
                                    datatype: 'json',
                                    type: 'POST',
                                    async: false,
                                    contentType: 'application/json; charset=utf-8',
                                    success: function (result) {
                                        if (result != null) {
                                            IsMultiLocation = result.IsAllowMultiLocation;
                                        }
                                    }
                                });


                                if (IsMultiLocation === false) {
                                    $('#pnlMainMenu').hide();
                                    toastr.warning(""Selected Segment Allowed only one Location."");
              ");
            WriteLiteral(@"                      return;
                                }

                                editRow = true;
                                $(""#pnlMainMenu"").show();
                                $("".mdl-card__title-text"").text(localization.AddBusinessLocation);
                                fnClearFields();

                                $('#txtBusinessEntityId').val(data.node.id.substring(2).split(""_"")[0]);
                                $('#txtBusinessSegmentId').val(data.node.id.substring(2).split(""_"")[1]);

                                fnFillComboTaxIdentification();

                                $('.BSCurrencyContainer').hide();
                                fnGridBSCurrency();

                                

                                $(""#btnAddBusinessLocation"").show();
                                $(""input,textarea"").attr('readonly', false);
                                $(""input[type=checkbox]"").attr('disabled', false);
                          ");
            WriteLiteral(@"      $(""#chkActiveStatus"").attr('disabled', true); 
                                $(""#btnAddBusinessLocation"").html('<i class=""fa fa-plus""></i> ' + localization.Save);
                            });
                        }
                        else if (data.node.id.startsWith(""FM"")) {

                            NodeID = 0;
                            NodeID = data.node.id.substring(2).split(""_"")[2];

                            $('#' + data.node.id + ""_anchor"").html($('#' + data.node.id + ""_anchor"").html() + '<span id=""View"" style=""padding-left:10px"">&nbsp;<i class=""fa fa-eye"" style=""color:#337ab7""aria-hidden=""true""></i></span>')
                            $('#' + data.node.id + ""_anchor"").html($('#' + data.node.id + ""_anchor"").html() + '<span id=""Edit"" style=""padding-left:10px"">&nbsp;<i class=""fa fa-pen"" style=""color:#337ab7""aria-hidden=""true""></i></span>')

                            $('#View').on('click', function () {

                                if (_userFormRole.IsView ===");
            WriteLiteral(@" false) {
                                    $('#pnlMainMenu').hide();
                                    toastr.warning(errorMsgCS[""E001""]);
                                    return;
                                }
                                editRow = false;
                                $(""#pnlMainMenu"").show();
                                $("".mdl-card__title-text"").text(localization.ViewBusinessLocation);
                                $('#txtBusinessLocationId').val(NodeID);
                                $('#txtBusinessEntityId').val(data.node.id.substring(2).split(""_"")[0]);
                                $('#txtBusinessSegmentId').val(data.node.id.substring(2).split(""_"")[1]);
                                fnFillComboTaxIdentification();
                                fnFillBusinessLocationInfo();

                                $(""#btnAddBusinessLocation"").hide();
                                $(""input,textarea"").attr('readonly', true);
                         ");
            WriteLiteral(@"       $(""input[type=checkbox]"").attr('disabled', true);
                                $(""#chkActiveStatus"").attr('disabled', true);
                            });

                            $('#Edit').on('click', function () {
                                if (_userFormRole.IsEdit === false) {
                                    $('#pnlMainMenu').hide();
                                    toastr.warning(errorMsgCS[""E002""]);
                                    return;
                                }
                                editRow = true;
                                $(""#pnlMainMenu"").show();
                                $("".mdl-card__title-text"").text(localization.EditBusinessLocation);
                                $('#txtBusinessLocationId').val(NodeID);
                                $('#txtBusinessEntityId').val(data.node.id.substring(2).split(""_"")[0]);
                                $('#txtBusinessSegmentId').val(data.node.id.substring(2).split(""_"")[1]);
     ");
            WriteLiteral(@"                           fnFillComboTaxIdentification();
                                fnFillBusinessLocationInfo();

                                $(""#btnAddBusinessLocation"").show();
                                $(""input,textarea"").attr('readonly', false);
                                $(""input[type=checkbox]"").attr('disabled', false);
                                $(""#chkActiveStatus"").attr('disabled', true);
                                $(""#btnAddBusinessLocation"").html('<i class=""fa fa-sync""></i> ' + localization.Update);
                            });
                        }
                        else {
                            fnClearFields();
                            $(""#pnlMainMenu"").hide();
                        }
                    }
                }
            }
        });

        $('#jstBusinessLocation').on(""close_node.jstree"", function (node) {
            var closingNode = node.handleObj.handler.arguments[1].node;
            $('#jstBusine");
            WriteLiteral(@"ssLocation').jstree().deselect_node(closingNode.children);
        });
        fnTreeSize(""#divJstBusinessLocation"");
    };

    function fnFillComboTaxIdentification() {
        $(""#cboTaxIdentification"").empty();
        $.ajax({
            type: 'POST',
            url: getBaseURL() + ""/BusinessStructure/GetTaxIdentificationByBSeg?BusinessId="" + $(""#txtBusinessEntityId"").val() + ""&SegmentId="" + $(""#txtBusinessSegmentId"").val(),
            success: function (result) {
                $(""#cboTaxIdentification"").append($(""<option value='0'>Select</option>""));
                if (result.length > 0)
                    $(""#dvTaxIdentification"").show();
                else
                    $(""#dvTaxIdentification"").hide();
                if (result != null) {
                    for (var i = 0; i < result.length; i++) {
                        $('#cboTaxIdentification').append('<option value=""' + result[i][""TaxIdentificationId""] + '"">' + result[i][""TaxIdentificationDesc""] + '</option>')");
            WriteLiteral(@";
                        //$(""#cboTaxIdentification"").append($(""<option></option>"").val(result[i][""TaxIdentificationId""]).html(result[i][""TaxIdentificationDesc""]));
                    }
                }
                $('#cboTaxIdentification').val(TaxId);
                $(""#cboTaxIdentification"").selectpicker('refresh');
            }
        });
        $('#cboTaxIdentification').val(TaxId);
        $(""#cboTaxIdentification"").selectpicker('refresh');
    }

    function fnFillBusinessLocationInfo() {
        if ($(""#txtBusinessLocationId"").val() != '' && $(""#txtBusinessLocationId"").val() != undefined) {
            $.ajax({
                async: false,
                url: getBaseURL() + ""/BusinessStructure/GetBusinessLocationInfo?BusinessId="" + $(""#txtBusinessEntityId"").val() + ""&SegmentId="" + $(""#txtBusinessSegmentId"").val() + ""&LocationId="" + $(""#txtBusinessLocationId"").val(),
                type: 'post',
                datatype: 'json',
                contentType: 'applicatio");
            WriteLiteral(@"n/json; charset=utf-8',
                success: function (result) {
                    $('#txtLocationcode').val(result.LocationCode);
                    $('#txtLocationDescription').val(result.LocationDescription);
                    $('#txtBusinessName').val(result.BusinessName);
                    $('#cboTaxIdentification').val(result.TaxIdentification);
                    $('#cboTaxIdentification').selectpicker('refresh');
                    TaxId = result.TaxIdentification;
                    $('#cboLicenseType').val(result.LicenseType);
                    $('#cboLicenseType').selectpicker('refresh');
                    $('#txtUserLicenses').val(result.UserLicenses);
                    $('#txtNoOfBeds').val(result.NoOfBeds);

                    $('.BSCurrencyContainer').hide();

                    if (result.ToLocalCurrency == 1) {
                        $(""#chkToLocalCurrency"").parent().addClass(""is-checked"");

                        $("".BSCurrencyContainer"").hide();
  ");
            WriteLiteral(@"                  }
                    else { $('#chkToLocalCurrency').parent().removeClass(""is-checked""); }

                    if (result.ToCurrCurrency == 1) {
                        $(""#chkToCurrCurrency"").parent().addClass(""is-checked"");

                        $('.BSCurrencyContainer').show();
                    }
                    else { $('#chkToCurrCurrency').parent().removeClass(""is-checked""); }

                    if (result.ToRealCurrency == 1) {
                        $(""#chkToRealCurrency"").parent().addClass(""is-checked"");

                        $('.BSCurrencyContainer').show();
                    }
                    else { $('#chkToRealCurrency').parent().removeClass(""is-checked""); }

                    fnGridBSCurrency();

                    if (result.ActiveStatus == 1) {
                        $(""#chkActiveStatus"").parent().addClass(""is-checked"");
                    }
                    else { $('#chkActiveStatus').parent().removeClass(""is-checked""); ");
            WriteLiteral(@"}

                    eSyaParams.ClearValue();
                    eSyaParams.SetJSONValue(result.l_FormParameter);
                }
            });
        }
    }

    function fnGridBSCurrency() {
        var URL = getBaseURL() + ""/BusinessStructure/GetBSCurrency?BusinessId="" + $(""#txtBusinessEntityId"").val() + ""&SegmentId="" + $(""#txtBusinessSegmentId"").val() + ""&LocationId="" + $(""#txtBusinessLocationId"").val();

        $(""#jqgBSCurrency"").jqGrid('GridUnload');
        $(""#jqgBSCurrency"").jqGrid({
            url: URL,
            mtype: 'Post',
            datatype: 'json',
            ajaxGridOptions: { contentType: 'application/json; charset=utf-8' },
            colNames: [""Currency Code"", localization.Currency, localization.Status],
            colModel: [
                { name: ""CurrencyCode"", width: 120, editable: false, align: 'left', hidden: true },
                { name: ""CurrencyName"", editable: false, width: 180, align: 'left', resizable: false },
                { na");
            WriteLiteral(@"me: ""ActiveStatus"", editable: true, width: 70, align: 'center', resizable: false, edittype: ""checkbox"", formatter: 'checkbox', editoptions: { value: ""true:false"" } }
            ],
            caption: """",
            height: 'auto',
            width: 'auto',
            rowNum: 15,
            rownumbers: true,
            viewrecords: true,
            gridview: true,
            autowidth: true,
            shrinkToFit: true,
            forceFit: true,
            cellEdit: true,
            loadonce: true,
            //onSelectRow: function (id) {
            //    if (id) { $('#jqgBSCurrency').jqGrid('editRow', id, true); }
            //},
            loadComplete: function () {
                var ids = $('#jqgBSCurrency').jqGrid('getDataIDs');
                var i = 0;
                if (editRow) {
                    for (i = 0; i < ids.length; i++) {
                        if (ids[i])
                            $('#jqgBSCurrency').jqGrid('editRow', ids[i]);
           ");
            WriteLiteral(@"         }
                }
            }

        });
    }

    function validationBusinessSegment() {
        if (IsStringNullorEmpty($(""#txtBusinessEntityId"").val())) {
            toastr.warning(""Please Select Business Entity"");
            return false;
        }
        if (IsStringNullorEmpty($(""#txtBusinessSegmentId"").val())) {
            toastr.warning(""Please Select Business Segment"");
            return false;
        }
        if (IsStringNullorEmpty($(""#txtLocationcode"").val())) {
            toastr.warning(""Please Select Location Code"");
            return false;
        }
        if (IsStringNullorEmpty($(""#txtLocationDescription"").val())) {
            toastr.warning(""Please Enter Location Description"");
            return false;
        }
        if (IsStringNullorEmpty($(""#txtBusinessName"").val())) {
            toastr.warning(""Please Enter Business Name"");
            return false;
        }

        if ($(""#cboTaxIdentification"").is("":visible"")) {
         ");
            WriteLiteral(@"   if ($(""#cboTaxIdentification"").val() === ""0"" || $(""#cboTaxIdentification"").val() === """") {
                toastr.warning(""Please Select Tax Identification"");
                return false;
            }
        }
    }

    function fnSaveBusinessLocation() {

        if (validationBusinessSegment() === false) {
            return;
        }
        $(""#btnAddBusinessLocation"").attr('disabled', true);
        var LocationId = $(""#txtBusinessLocationId"").val();

        var BusinessLocation;
        if (LocationId == null || LocationId == """") {
            BusinessLocation = {
                BusinessId: $(""#txtBusinessEntityId"").val(),
                SegmentId: $(""#txtBusinessSegmentId"").val(),
                LocationId: 0,
                LocationCode: $(""#txtLocationcode"").val(),
                LocationDescription: $(""#txtLocationDescription"").val(),
                BusinessName: $(""#txtBusinessName"").val(),
                TaxIdentification: $(""#cboTaxIdentification"").val(),
");
            WriteLiteral(@"                LicenseType: $(""#cboLicenseType"").val(),
                UserLicenses: $(""#txtUserLicenses"").val(),
                NoOfBeds: $(""#txtNoOfBeds"").val(),
                ToLocalCurrency: $(""#chkToLocalCurrency"").parent().hasClass(""is-checked""),
                ToCurrCurrency: $(""#chkToCurrCurrency"").parent().hasClass(""is-checked""),
                ToRealCurrency: $(""#chkToRealCurrency"").parent().hasClass(""is-checked""),
                ActiveStatus: $(""#chkActiveStatus"").parent().hasClass(""is-checked"")
            };

        }
        else {
            BusinessLocation = {
                BusinessId: $(""#txtBusinessEntityId"").val(),
                SegmentId: $(""#txtBusinessSegmentId"").val(),
                LocationId: $(""#txtBusinessLocationId"").val(),
                LocationCode: $(""#txtLocationcode"").val(),
                LocationDescription: $(""#txtLocationDescription"").val(),
                BusinessName: $(""#txtBusinessName"").val(),
                TaxIdentification: $");
            WriteLiteral(@"(""#cboTaxIdentification"").val(),
                LicenseType: $(""#cboLicenseType"").val(),
                UserLicenses: $(""#txtUserLicenses"").val(),
                NoOfBeds: $(""#txtNoOfBeds"").val(),
                ToLocalCurrency: $(""#chkToLocalCurrency"").parent().hasClass(""is-checked""),
                ToCurrCurrency: $(""#chkToCurrCurrency"").parent().hasClass(""is-checked""),
                ToRealCurrency: $(""#chkToRealCurrency"").parent().hasClass(""is-checked""),
                ActiveStatus: $(""#chkActiveStatus"").parent().hasClass(""is-checked"")
            };
        }

        var bsCurrency = [];
        var jqgBSCurrency = jQuery(""#jqgBSCurrency"").jqGrid('getRowData');

        for (var i = 0; i < jqgBSCurrency.length; ++i) {
            if (parseFloat(jqgBSCurrency[i][""CurrencyCode""]) != '') {
                bsCurrency.push({
                    CurrencyCode: jqgBSCurrency[i][""CurrencyCode""],
                    ActiveStatus: jqgBSCurrency[i][""ActiveStatus""]
                });
    ");
            WriteLiteral(@"        }
        }
        
        BusinessLocation.l_BSCurrency = bsCurrency;

        var fmParams = eSyaParams.GetJSONValue();
        BusinessLocation.l_FormParameter = fmParams;

        $.ajax({
            url: getBaseURL() + '/BusinessStructure/InsertOrUpdateBusinessLocation',
            type: 'POST',
            datatype: 'json',
            data: { BusinessLocation },
            success: function (response) {
                if (response.Status) {
                    toastr.success(response.Message);
                    location.reload();
                    return true;
                }
                else {
                    toastr.error(response.Message);
                    $(""#btnAddBusinessLocation"").attr('disabled', false);
                    return false;
                }
            },
            error: function (error) {
                $(""#btnAddBusinessLocation"").attr('disabled', false);
                toastr.error(error.statusText);
            }");
            WriteLiteral(@"
        });
    }

    function validationBusinessSegmentOnDelete() {

        if (IsStringNullorEmpty($(""#txtBusinessEntityId"").val())) {
            toastr.warning(""Please Select Business Entity"");
            return false;
        }
        if (IsStringNullorEmpty($(""#txtBusinessSegmentId"").val())) {
            toastr.warning(""Please Select Business Segment"");
            return false;
        }
        if (IsStringNullorEmpty($(""#txtBusinessLocationId"").val())) {
            toastr.warning(""Please Select Business Location"");
            return false;
        }
        if (IsStringNullorEmpty($(""#txtLocationDescription"").val())) {
            toastr.warning(""Please Enter Location Description"");
            return false;
        }
        //if ($(""#cboTaxIdentification"").val() === ""0"" || $(""#cboTaxIdentification"").val() === """") {
        //    toastr.warning(""Please Select Tax Identification"");
        //    return false;
        //}
        if ($(""#cboLicenseType"").val() === ""0"" ");
            WriteLiteral(@"|| $(""#cboLicenseType"").val() === """") {
            toastr.warning(""Please Select License Type"");
            return false;
        }
    }

    function fnClearFields() {
        $(""#txtBusinessEntityId"").val('');
        $(""#txtBusinessSegmentId"").val('');
        $(""#txtBusinessLocationId"").val('');
        $(""#txtLocationcode"").val('');
        $(""#txtLocationDescription"").val('');
        $(""#txtBusinessName"").val('');
        $(""#cboTaxIdentification"").val('0');
        $(""#cboTaxIdentification"").selectpicker('refresh');
        $(""#cboLicenseType"").val('0');
        $(""#cboLicenseType"").selectpicker('refresh');
        $(""#txtUserLicenses"").val('0');
        $(""#txtNoOfBeds"").val('0');
        $(""#chkToRealCurrency"").parent().removeClass(""is-checked"");
        $(""#chkToCurrCurrency"").parent().removeClass(""is-checked"");
        $(""#chkToLocalCurrency"").parent().removeClass(""is-checked"");
        $(""#chkActiveStatus"").parent().addClass(""is-checked"");
    }
    
    function fnDel");
            WriteLiteral(@"eteNode() {

        if (validationBusinessSegmentOnDelete() === false) {
            return;
        }
        $(""#btnDeleteNode"").attr('disabled', true);
        $.ajax({
            url: getBaseURL() + '/BusinessStructure/DeleteBusinessLocation?BusinessId=' + $(""#txtBusinessEntityId"").val() + ""&SegmentId="" + $(""#txtBusinessSegmentId"").val() + ""&LocationId="" + $(""#txtBusinessLocationId"").val(),
            type: 'POST',
            datatype: 'json',
            success: function (response) {
                if (response.Status) {
                    toastr.success(response.Message);
                    location.reload();
                    return true;
                }
                else {
                    toastr.error(response.Message);
                    return false;
                }

            },
            error: function (error) {
                toastr.error(error.statusText);
            }
        });
    }

    function fnExpandAll() {
        $('#jstBusines");
            WriteLiteral(@"sLocation').jstree('open_all');
    }
    function fnCollapseAll() {
        fnClearFields();
        $(""#pnlMainMenu"").hide();
        $('#jstBusinessLocation').jstree('close_all');
    }
    function fnTreeSize() {
        $(""#jstBusinessLocation"").css({
            'height': $(window).innerHeight() - 136,
            'overflow': 'auto'
        });
    }

    function fnToLocalCurrency(elem) {
        if (elem.checked) {
            $(""#chkToLocalCurrency"").parent().addClass(""is-checked"");
            //$('#chkToCurrCurrency').parent().removeClass(""is-checked"");
            //$('#chkToRealCurrency').parent().removeClass(""is-checked"");
            //$("".BSCurrencyContainer"").hide();
        }
    }

    function fnToCurrCurrency(elem) {
        if (elem.checked) {
            $(""#chkToCurrCurrency"").parent().addClass(""is-checked"");
            //$('#chkToLocalCurrency').parent().removeClass(""is-checked"");
            $('#chkToRealCurrency').parent().removeClass(""is-checked"");
    ");
            WriteLiteral(@"        $('.BSCurrencyContainer').show();
        }
        else {
            $('.BSCurrencyContainer').hide();
        }
    }

    function fnToRealCurrency(elem) {
        if (elem.checked) {
            $(""#chkToRealCurrency"").parent().addClass(""is-checked"");
            //$('#chkToLocalCurrency').parent().removeClass(""is-checked"");
            $('#chkToCurrCurrency').parent().removeClass(""is-checked"");
            $('.BSCurrencyContainer').show();
        }
        else {
            $('.BSCurrencyContainer').hide();
        }
    }

</script>


");
            EndContext();
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public IViewLocalizer Localizer { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<dynamic> Html { get; private set; }
    }
}
#pragma warning restore 1591
