#pragma checksum "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\eSyaPatientPortal\Views\PreRegistration\Index.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "4681204833e51dec4049199d6df6016a8a61d3a3"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.Areas_eSyaPatientPortal_Views_PreRegistration_Index), @"mvc.1.0.view", @"/Areas/eSyaPatientPortal/Views/PreRegistration/Index.cshtml")]
[assembly:global::Microsoft.AspNetCore.Mvc.Razor.Compilation.RazorViewAttribute(@"/Areas/eSyaPatientPortal/Views/PreRegistration/Index.cshtml", typeof(AspNetCore.Areas_eSyaPatientPortal_Views_PreRegistration_Index))]
namespace AspNetCore
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"4681204833e51dec4049199d6df6016a8a61d3a3", @"/Areas/eSyaPatientPortal/Views/PreRegistration/Index.cshtml")]
    public class Areas_eSyaPatientPortal_Views_PreRegistration_Index : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<dynamic>
    {
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_0 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("href", new global::Microsoft.AspNetCore.Html.HtmlString("~/css/eSyaPatientPortal/preRegistration.css"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_1 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("rel", new global::Microsoft.AspNetCore.Html.HtmlString("stylesheet"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_2 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("src", new global::Microsoft.AspNetCore.Html.HtmlString("~/images/logo/esya-logo-whitebg.jpeg"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_3 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("class", new global::Microsoft.AspNetCore.Html.HtmlString("img-responsive MasterPage-Logo"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_4 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("asp-area", "", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_5 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("asp-controller", "Home", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_6 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("asp-action", "Index", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_7 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("class", new global::Microsoft.AspNetCore.Html.HtmlString("navbar-brand"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_8 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("value", "0", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_9 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("value", "M", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_10 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("value", "F", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_11 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("value", "S", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_12 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("value", "1", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_13 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("value", "2", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_14 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("class", new global::Microsoft.AspNetCore.Html.HtmlString("w-100 selectpicker"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_15 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("data-live-search", new global::Microsoft.AspNetCore.Html.HtmlString("false"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_16 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("id", new global::Microsoft.AspNetCore.Html.HtmlString("cboMotherTongue"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_17 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("title", new global::Microsoft.AspNetCore.Html.HtmlString("Select"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_18 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("data-size", new global::Microsoft.AspNetCore.Html.HtmlString("8"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_19 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("value", "3", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_20 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("id", new global::Microsoft.AspNetCore.Html.HtmlString("cboReffferedby"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        #line hidden
        #pragma warning disable 0169
        private string __tagHelperStringValueBuffer;
        #pragma warning restore 0169
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext __tagHelperExecutionContext;
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner __tagHelperRunner = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner();
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __backed__tagHelperScopeManager = null;
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __tagHelperScopeManager
        {
            get
            {
                if (__backed__tagHelperScopeManager == null)
                {
                    __backed__tagHelperScopeManager = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager(StartTagHelperWritingScope, EndTagHelperWritingScope);
                }
                return __backed__tagHelperScopeManager;
            }
        }
        private global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper;
        private global::Microsoft.AspNetCore.Mvc.TagHelpers.AnchorTagHelper __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper;
        private global::Microsoft.AspNetCore.Mvc.TagHelpers.OptionTagHelper __Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper;
        private global::Microsoft.AspNetCore.Mvc.TagHelpers.SelectTagHelper __Microsoft_AspNetCore_Mvc_TagHelpers_SelectTagHelper;
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            BeginContext(54, 2, true);
            WriteLiteral("\r\n");
            EndContext();
#line 3 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\eSyaPatientPortal\Views\PreRegistration\Index.cshtml"
  
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_PatientLayout.cshtml";

#line default
#line hidden
            BeginContext(230, 76, false);
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("link", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.SelfClosing, "4681204833e51dec4049199d6df6016a8a61d3a310532", async() => {
            }
            );
            __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_0);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_1);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            EndContext();
            BeginContext(306, 315, true);
            WriteLiteral(@"
<style>
    nav{
        display:none !important;
    }
</style>
<script>

    var _cnfISDCode = ""91"";
    $(function () {
        _cnfISDCode = ""91"";
    });
</script>

<section class=""section_PreRegistration"">
    <div class=""row pt-2 mb-3"">
        <div class=""col-12 text-center"">
            ");
            EndContext();
            BeginContext(621, 202, false);
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("a", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "4681204833e51dec4049199d6df6016a8a61d3a312110", async() => {
                BeginContext(698, 18, true);
                WriteLiteral("\r\n                ");
                EndContext();
                BeginContext(716, 89, false);
                __tagHelperExecutionContext = __tagHelperScopeManager.Begin("img", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.SelfClosing, "4681204833e51dec4049199d6df6016a8a61d3a312506", async() => {
                }
                );
                __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper>();
                __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_2);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_3);
                await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
                if (!__tagHelperExecutionContext.Output.IsContentModified)
                {
                    await __tagHelperExecutionContext.SetOutputContentAsync();
                }
                Write(__tagHelperExecutionContext.Output);
                __tagHelperExecutionContext = __tagHelperScopeManager.End();
                EndContext();
                BeginContext(805, 14, true);
                WriteLiteral("\r\n            ");
                EndContext();
            }
            );
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.AnchorTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper);
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.Area = (string)__tagHelperAttribute_4.Value;
            __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_4);
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.Controller = (string)__tagHelperAttribute_5.Value;
            __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_5);
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.Action = (string)__tagHelperAttribute_6.Value;
            __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_6);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_7);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            EndContext();
            BeginContext(823, 1178, true);
            WriteLiteral(@"
        </div>
        <div class=""col-lg-12 col-md-12 col-sm-12"">
            <p class=""_preg_mainheading"">Pre Registration</p>

        </div>
        <div class=""col-lg-12 col-md-12 col-sm-12 form-group"">
            <p class=""heading_preRegistration""><i class=""fa fa-file""></i> Demographic Details</p>

        </div>
        <div class=""col-lg-4 col-md-4 col-sm-6 form-group"">
            <label>First Name</label>
            <input type=""text"" name=""First name"" class=""form-control"" id=""txtFirstName"" maxlength=""50"" />
        </div>
        <div class=""col-lg-4 col-md-4 col-sm-6 form-group"">
            <label>Middle Name</label>
            <input type=""text"" name=""Middle name"" class=""form-control"" id=""txtMiddleName"" maxlength=""50"" />
        </div>
        <div class=""col-lg-4 col-md-4 col-sm-6 form-group"">
            <label>Last Name</label>
            <input type=""text"" name=""Last name"" class=""form-control"" id=""txtLastName"" maxlength=""50"" />
        </div>
        <div class=""co");
            WriteLiteral("l-lg-2 col-md-4 col-sm-6 form-group\">\r\n            <label>Gender</label>\r\n            <select class=\"w-100 selectpicker\" id=\"cboGender\">\r\n                ");
            EndContext();
            BeginContext(2001, 33, false);
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("option", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "4681204833e51dec4049199d6df6016a8a61d3a316593", async() => {
                BeginContext(2019, 6, true);
                WriteLiteral("Select");
                EndContext();
            }
            );
            __Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.OptionTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper);
            __Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper.Value = (string)__tagHelperAttribute_8.Value;
            __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_8);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            EndContext();
            BeginContext(2034, 18, true);
            WriteLiteral("\r\n                ");
            EndContext();
            BeginContext(2052, 31, false);
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("option", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "4681204833e51dec4049199d6df6016a8a61d3a317987", async() => {
                BeginContext(2070, 4, true);
                WriteLiteral("Male");
                EndContext();
            }
            );
            __Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.OptionTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper);
            __Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper.Value = (string)__tagHelperAttribute_9.Value;
            __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_9);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            EndContext();
            BeginContext(2083, 18, true);
            WriteLiteral("\r\n                ");
            EndContext();
            BeginContext(2101, 33, false);
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("option", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "4681204833e51dec4049199d6df6016a8a61d3a319379", async() => {
                BeginContext(2119, 6, true);
                WriteLiteral("Female");
                EndContext();
            }
            );
            __Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.OptionTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper);
            __Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper.Value = (string)__tagHelperAttribute_10.Value;
            __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_10);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            EndContext();
            BeginContext(2134, 637, true);
            WriteLiteral(@"
            </select>
        </div>
        <div class=""col-lg-2 col-md-4 col-sm-6 form-group"">
            <label>Age</label>
            <input type=""text"" name=""number"" class=""form-control"" id=""txtAge"" maxlength=""5"" />
        </div>
        <div class=""col-lg-2 col-md-4 col-sm-6 form-group"">
            <label>DOB</label>
            <input type=""text"" name=""DOB"" class=""form-control datepicker"" id=""dtDob"" />
        </div>

        <div class=""col-lg-2 col-md-4 col-sm-6 form-group"">
            <label>Marital Status</label>
            <select class=""w-100 selectpicker"" id=""cboMaritalStatus"">
                ");
            EndContext();
            BeginContext(2771, 33, false);
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("option", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "4681204833e51dec4049199d6df6016a8a61d3a321422", async() => {
                BeginContext(2789, 6, true);
                WriteLiteral("Select");
                EndContext();
            }
            );
            __Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.OptionTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper);
            __Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper.Value = (string)__tagHelperAttribute_8.Value;
            __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_8);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            EndContext();
            BeginContext(2804, 18, true);
            WriteLiteral("\r\n                ");
            EndContext();
            BeginContext(2822, 34, false);
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("option", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "4681204833e51dec4049199d6df6016a8a61d3a322816", async() => {
                BeginContext(2840, 7, true);
                WriteLiteral("Married");
                EndContext();
            }
            );
            __Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.OptionTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper);
            __Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper.Value = (string)__tagHelperAttribute_9.Value;
            __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_9);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            EndContext();
            BeginContext(2856, 18, true);
            WriteLiteral("\r\n                ");
            EndContext();
            BeginContext(2874, 33, false);
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("option", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "4681204833e51dec4049199d6df6016a8a61d3a324211", async() => {
                BeginContext(2892, 6, true);
                WriteLiteral("Single");
                EndContext();
            }
            );
            __Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.OptionTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper);
            __Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper.Value = (string)__tagHelperAttribute_11.Value;
            __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_11);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            EndContext();
            BeginContext(2907, 448, true);
            WriteLiteral(@"
            </select>
        </div>
        <div class=""col-lg-2 col-md-4 col-sm-6 form-group"">
            <label>Number of Children</label>
            <input type=""text"" name=""number"" class=""form-control"" id=""txtNoofChildren"" maxlength=""10"" />
        </div>
        <div class=""col-lg-2 col-md-4 form-group"">
            <label>Nationality</label>
            <select class=""w-100 selectpicker"" id=""cboNationality"">
                ");
            EndContext();
            BeginContext(3355, 33, false);
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("option", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "4681204833e51dec4049199d6df6016a8a61d3a326055", async() => {
                BeginContext(3373, 6, true);
                WriteLiteral("Select");
                EndContext();
            }
            );
            __Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.OptionTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper);
            __Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper.Value = (string)__tagHelperAttribute_8.Value;
            __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_8);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            EndContext();
            BeginContext(3388, 18, true);
            WriteLiteral("\r\n                ");
            EndContext();
            BeginContext(3406, 33, false);
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("option", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "4681204833e51dec4049199d6df6016a8a61d3a327449", async() => {
                BeginContext(3424, 6, true);
                WriteLiteral("Indian");
                EndContext();
            }
            );
            __Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.OptionTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper);
            __Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper.Value = (string)__tagHelperAttribute_12.Value;
            __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_12);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            EndContext();
            BeginContext(3439, 18, true);
            WriteLiteral("\r\n                ");
            EndContext();
            BeginContext(3457, 35, false);
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("option", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "4681204833e51dec4049199d6df6016a8a61d3a328845", async() => {
                BeginContext(3475, 8, true);
                WriteLiteral("American");
                EndContext();
            }
            );
            __Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.OptionTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper);
            __Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper.Value = (string)__tagHelperAttribute_13.Value;
            __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_13);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            EndContext();
            BeginContext(3492, 370, true);
            WriteLiteral(@"
            </select>
        </div>
        <div class=""col-lg-4 col-md-4 col-sm-6 form-group"">
            <label>Occupation</label>
            <input type=""text"" class=""form-control"" id=""txtOccupation"" maxlength=""150"" />
        </div>

        <div class=""col-lg-4 col-md-4 col-sm-6 form-group"">
            <label>Preferred Language</label>
            ");
            EndContext();
            BeginContext(3862, 222, false);
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("select", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "4681204833e51dec4049199d6df6016a8a61d3a330608", async() => {
                BeginContext(4010, 18, true);
                WriteLiteral("\r\n                ");
                EndContext();
                BeginContext(4028, 33, false);
                __tagHelperExecutionContext = __tagHelperScopeManager.Begin("option", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "4681204833e51dec4049199d6df6016a8a61d3a331011", async() => {
                    BeginContext(4046, 6, true);
                    WriteLiteral("Select");
                    EndContext();
                }
                );
                __Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.OptionTagHelper>();
                __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper);
                __Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper.Value = (string)__tagHelperAttribute_8.Value;
                __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_8);
                await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
                if (!__tagHelperExecutionContext.Output.IsContentModified)
                {
                    await __tagHelperExecutionContext.SetOutputContentAsync();
                }
                Write(__tagHelperExecutionContext.Output);
                __tagHelperExecutionContext = __tagHelperScopeManager.End();
                EndContext();
                BeginContext(4061, 14, true);
                WriteLiteral("\r\n            ");
                EndContext();
            }
            );
            __Microsoft_AspNetCore_Mvc_TagHelpers_SelectTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.SelectTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_SelectTagHelper);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_14);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_15);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_16);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_17);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_18);
#line 93 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\eSyaPatientPortal\Views\PreRegistration\Index.cshtml"
__Microsoft_AspNetCore_Mvc_TagHelpers_SelectTagHelper.Items = ViewBag.MotherTongueList;

#line default
#line hidden
            __tagHelperExecutionContext.AddTagHelperAttribute("asp-items", __Microsoft_AspNetCore_Mvc_TagHelpers_SelectTagHelper.Items, global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            EndContext();
            BeginContext(4084, 344, true);
            WriteLiteral(@"
        </div>
    </div>
    <div class=""row mb-3"">
        <div class=""col-lg-12 col-md-12 col-sm-12 form-group"">
            <p class=""heading_preRegistration""><i class=""fa fa-phone""></i> Contact Details</p>
        </div>

        <div class=""col-lg-4 col-md-4 col-sm-6 form-group"">
            <label>Mobile</label>
            ");
            EndContext();
            BeginContext(4429, 70, false);
#line 105 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\eSyaPatientPortal\Views\PreRegistration\Index.cshtml"
       Write(await Component.InvokeAsync("IsdMobileInput", new { id = "MobileNo" }));

#line default
#line hidden
            EndContext();
            BeginContext(4499, 1448, true);
            WriteLiteral(@"

        </div>
        <div class=""col-lg-8 col-md-8 col-sm-4 form-group"">
            <label>Email ID</label>
            <input type=""text"" class=""form-control"" id=""txtEmailId"" maxlength=""50"" />
        </div>

        <div class=""col-lg-12 col-md-12 col-sm-12 form-group"">
            <label>Address</label>
            <input name=""Address"" class=""form-control"" id=""txtAddress"" maxlength=""250"">
        </div>
        <div class=""col-lg-4 col-md-4 col-sm-4 form-group"">
            <label>City</label>
            <input type=""text"" class=""form-control"" id=""txtCity"" />
        </div>
        <div class=""col-lg-4 col-md-4 col-sm-6 form-group"">
            <label>PinCode</label>
            <input type=""text"" name=""number"" class=""form-control"" id=""txtPinCode"" maxlength=""10"" />
        </div>
        <div class=""col-lg-4 col-md-4 col-sm-6 form-group"">
            <label>Area Code</label>
            <input type=""text"" name=""number"" class=""form-control"" id=""txtAreaCode"" maxlength=""10"" />
  ");
            WriteLiteral(@"      </div>

    </div>
    <div class=""row mb-3"">
        <div class=""col-lg-12 col-md-12 col-sm-12 form-group"">
            <p class=""heading_preRegistration""><i class=""fa fa-user""></i> Relationship Details</p>
        </div>
        <div class=""col-lg-4 col-md-4 col-sm-6 form-group"">
            <label>RelationShip</label>
            <select class=""w-100 selectpicker"" id=""cboRelationShip"">
                ");
            EndContext();
            BeginContext(5947, 33, false);
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("option", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "4681204833e51dec4049199d6df6016a8a61d3a336508", async() => {
                BeginContext(5965, 6, true);
                WriteLiteral("Select");
                EndContext();
            }
            );
            __Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.OptionTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper);
            __Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper.Value = (string)__tagHelperAttribute_8.Value;
            __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_8);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            EndContext();
            BeginContext(5980, 18, true);
            WriteLiteral("\r\n                ");
            EndContext();
            BeginContext(5998, 33, false);
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("option", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "4681204833e51dec4049199d6df6016a8a61d3a337902", async() => {
                BeginContext(6016, 6, true);
                WriteLiteral("Friend");
                EndContext();
            }
            );
            __Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.OptionTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper);
            __Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper.Value = (string)__tagHelperAttribute_12.Value;
            __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_12);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            EndContext();
            BeginContext(6031, 18, true);
            WriteLiteral("\r\n                ");
            EndContext();
            BeginContext(6049, 36, false);
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("option", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "4681204833e51dec4049199d6df6016a8a61d3a339298", async() => {
                BeginContext(6067, 9, true);
                WriteLiteral("Neighbour");
                EndContext();
            }
            );
            __Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.OptionTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper);
            __Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper.Value = (string)__tagHelperAttribute_13.Value;
            __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_13);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            EndContext();
            BeginContext(6085, 18, true);
            WriteLiteral("\r\n                ");
            EndContext();
            BeginContext(6103, 35, false);
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("option", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "4681204833e51dec4049199d6df6016a8a61d3a340697", async() => {
                BeginContext(6121, 8, true);
                WriteLiteral("Relative");
                EndContext();
            }
            );
            __Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.OptionTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper);
            __Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper.Value = (string)__tagHelperAttribute_19.Value;
            __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_19);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            EndContext();
            BeginContext(6138, 369, true);
            WriteLiteral(@"
            </select>
        </div>
        <div class=""col-lg-4 col-md-4 col-sm-6 form-group"">
            <label>Relation Name</label>
            <input type=""text"" class=""form-control"" id=""txtRelationName"" maxlength=""150"" />
        </div>

        <div class=""col-lg-4 col-md-4 col-sm-6 form-group"">
            <label>Referred by:</label>
            ");
            EndContext();
            BeginContext(6507, 219, false);
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("select", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "4681204833e51dec4049199d6df6016a8a61d3a342459", async() => {
                BeginContext(6652, 18, true);
                WriteLiteral("\r\n                ");
                EndContext();
                BeginContext(6670, 33, false);
                __tagHelperExecutionContext = __tagHelperScopeManager.Begin("option", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "4681204833e51dec4049199d6df6016a8a61d3a342862", async() => {
                    BeginContext(6688, 6, true);
                    WriteLiteral("Select");
                    EndContext();
                }
                );
                __Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.OptionTagHelper>();
                __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper);
                __Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper.Value = (string)__tagHelperAttribute_8.Value;
                __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_8);
                await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
                if (!__tagHelperExecutionContext.Output.IsContentModified)
                {
                    await __tagHelperExecutionContext.SetOutputContentAsync();
                }
                Write(__tagHelperExecutionContext.Output);
                __tagHelperExecutionContext = __tagHelperScopeManager.End();
                EndContext();
                BeginContext(6703, 14, true);
                WriteLiteral("\r\n            ");
                EndContext();
            }
            );
            __Microsoft_AspNetCore_Mvc_TagHelpers_SelectTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.SelectTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_SelectTagHelper);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_14);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_15);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_20);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_17);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_18);
#line 151 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\eSyaPatientPortal\Views\PreRegistration\Index.cshtml"
__Microsoft_AspNetCore_Mvc_TagHelpers_SelectTagHelper.Items = ViewBag.RefferedByList;

#line default
#line hidden
            __tagHelperExecutionContext.AddTagHelperAttribute("asp-items", __Microsoft_AspNetCore_Mvc_TagHelpers_SelectTagHelper.Items, global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            EndContext();
            BeginContext(6726, 6458, true);
            WriteLiteral(@"
        </div>
    </div>
    <div class=""row mb-3"">
        <div class=""col-lg-12 col-md-12 col-sm-12 form-group"">
            <p class=""heading_preRegistration""><i class=""fa fa-info-circle""></i> Other Details</p>
        </div>

        <div class=""col-lg-12 col-md-12 form-group"">

            <label>Present Complaint</label>
            <input type=""text"" class=""form-control"" id=""txtPresentComplaint"" maxlength=""150"" />
        </div>

        <div class=""col-lg-4 col-md-4 col-sm-6 form-group"">
            <label>Pre Existing Health Condition</label>
            <input type=""text"" name=""Firstname"" class=""form-control"" id=""txtPreExistingHealthCondition"" maxlength=""50"" />
        </div>
        <div class=""col-lg-4 col-md-4 col-sm-6 form-group"">
            <label>RUHID</label>
            <input type=""text"" name=""number"" class=""form-control"" id=""txtRUHID"" maxlength=""50"" />
        </div>
        <div class=""col-lg-4 col-md-4 col-sm-6 form-group"">
            <label class=""mdl-checkbox");
            WriteLiteral(@" mdl-js-checkbox mdl-js-ripple-effect"" for=""chkActiveStatus"">
                <input type=""checkbox"" id=""chkActiveStatus"" class=""mdl-checkbox__input"">
                <span class=""mdl-checkbox__label""> Active Status</span>
            </label>
        </div>
        <div class=""col-lg-12 col-md-12 col-sm-12 text-center"">
            <hr />
            <button type=""button"" class=""btn btn-primary mr-10"" id=""btnSavePatientRegistration"" onclick=""fnSavePatientRegistration()""> <i class=""fa fa-save""></i>  Save</button>
            <button type=""button"" class=""btn btn-primary  cancel-button"" id=""btnPatientRegistrationCancel"">Cancel</button>
        </div>
    </div>
</section>
<script>

    $(document).ready(function () {
        $(""#chkActiveStatus"").parent().addClass(""is-checked"");
    });
    //$("".ComplaintSelecteCheckBox"").change(function () {
    //    var checkboxid = $(this).attr(""id"");
    //    var txtboxid = checkboxid.substring(3);
    //    if (this.checked) {

    //        $(""#tx");
            WriteLiteral(@"t"" + txtboxid).attr(""disabled"", false);
    //    }
    //    else {
    //        $(""#txt"" + txtboxid).val('');
    //        $(""#txt"" + txtboxid).attr(""disabled"", true);
    //    }
    //});

    $('input[name=""number""]').keyup(function (e) {
        if (/\D/g.test(this.value)) {
            // Filter non-digits from input value.
            this.value = this.value.replace(/\D/g, '');
        }
    });

    function fnSavePatientRegistration() {

        if (IsValidSavePatientRegistration() === false) {
            return;
        }

        debugger;


        //var Complaintschected = [];

        //$(""[name='chkComplaintslistitem']"").each(function (index, data) {
        //    if (data.checked) {
        //        Complaintschected.push(data.value);
        //    }
        //});



        //var PersonalInfoList = [];

        //$(""[name='txtPersonalInfo']"").each(function (index, data) {
        //    if (!IsStringNullorEmpty(data.value)) {
        //        Persona");
            WriteLiteral(@"lInfoList.push(data.value);
        //    }

        //});



        //var StrPersonalInfo = [];
        //if (Complaintschected.length !== 0 && PersonalInfoList.length !== 0) {
        //    var key = Complaintschected,
        //        value = PersonalInfoList,
        //        StrPersonalInfo = JSON.stringify(key.reduce((p, c, i) => { p[c] = value[i]; return p }, {}));
        //}

        //var Languagechected = [];

        //$(""[name='chkLanguagelistitem']"").each(function (index, data) {
        //    if (data.checked) {
        //        Languagechected.push(data.value);
        //    }
        //});

        //Languagechected = Languagechected.toString();

        var obj = {
            BusinessKey: 0,
            Prkey: 0,
            //Prdate:0,
            PatientFirstName: $(""#txtFirstName"").val(),
            PatientMiddleName: $(""#txtMiddleName"").val(),
            PatientLastName: $(""#txtLastName"").val(),
            Gender: $(""#cboGender"").val(),
           ");
            WriteLiteral(@" AgeYy: $(""#txtAge"").val(),
            DateOfBirth: $(""#dtDob"").val(),
            MaritalStatus: $(""#cboMaritalStatus"").val(),
            NoOfChildren: $(""#txtNoofChildren"").val(),
            Isdcode: $(""#cboMobileNo"").val(),
            MobileNumber: $(""#txtMobileNo"").val(),
            EmailId: $(""#txtEmailId"").val(),
            Nationality: $(""#cboNationality"").val(),
            Address: $(""#txtAddress"").val(),
            //City: $(""#txtCity"").val(),
            City: 0,
            Pincode: $(""#txtPinCode"").val(),
            AreaCode: $(""#txtAreaCode"").val(),
            Occupation: $(""#txtOccupation"").val(),
            PreferredLanguage: $(""#cboMotherTongue"").val(),
            Relationship: $(""#cboRelationShip"").val(),
            RelationName: $(""#txtRelationName"").val(),
            ReferredBy: $(""#cboReffferedby"").val(),
            PresentComplaints: $(""#txtPresentComplaint"").val(),
            PreExistingHealthCondition: $(""#txtPreExistingHealthCondition"").val(),
      ");
            WriteLiteral(@"      //PersonalInfo: StrPersonalInfo,
            //SpeakingLanguages: Languagechected,
            RUhid: $(""#txtRUHID"").val(),
            ActiveStatus: $(""#chkActiveStatus"").parent().hasClass(""is-checked"")

        };
        $(""#btnSavePatientRegistration"").attr('disabled', true);
        $.ajax({
            url: getBaseURL() + '/PreRegistration/InsertPatientPreRegistration',
            type: 'POST',
            datatype: 'json',
            data: { obj },
            success: function (response) {
                if (response.Status) {
                    toastr.success(response.Message);
                    $(""#btnSavePatientRegistration"").attr('disabled', false);
                    fnClearPatientRegistrationFields();
                    return true;
                }
                else {
                    toastr.error(response.Message);
                    $(""#btnSavePatientRegistration"").attr('disabled', false);
                    return false;
                }

    ");
            WriteLiteral(@"        },
            error: function (error) {
                toastr.error(error.statusText);
                $(""#btnSavePatientRegistration"").attr('disabled', false);
            }
        });

    }

    function IsValidSavePatientRegistration() {

        var EmailPattern = /^\w+([-+.'][^\s]\w+)*");
            EndContext();
            BeginContext(13185, 3723, true);
            WriteLiteral(@"@\w+([-.]\w+)*\.\w+([-.]\w+)*$/;
        if (IsStringNullorEmpty($(""#txtFirstName"").val())) {
            toastr.warning(""Please Enter First Name"");
            return false;
        }
        if (IsStringNullorEmpty($(""#txtLastName"").val())) {
            toastr.warning(""Please Enter Last Name"");
            return false;
        }

        if ($(""#cboGender"").val() == 0 || $(""#cboGender"").val() == ""0"") {
            toastr.warning(""Please Select Gender"");
            return false;
        }
        if (IsStringNullorEmpty($(""#txtAge"").val())) {
            toastr.warning(""Please Enter Age"");
            return false;
        }
        if (IsStringNullorEmpty($(""#dtDob"").val())) {
            toastr.warning(""Please Select Date of Birth"");
            return false;
        }
        if ($(""#cboMotherTongue"").val() == 0 || $(""#cboMotherTongue"").val() == ""0"") {
            toastr.warning(""Please select Preferred Language"");
            return false;
        }
        if (IsStringNullor");
            WriteLiteral(@"Empty($(""#cboMobileNo"").val()) || $(""#cboMobileNo"").val() == 0 || $(""#cboMobileNo"").val() == ""0"") {
            toastr.warning(""Please Select ISD Code"");
            return false;
        }
        if (IsStringNullorEmpty($(""#txtMobileNo"").val())) {
            toastr.warning(""Please Enter Mobile Number"");
            return false;
        }
        if (!IsStringNullorEmpty($(""#txtEmailId"").val())) {

            if (!EmailPattern.test($(""#txtEmailId"").val())) {
                toastr.warning(""Email ID is Not Valid"");
                $('#txtEmailId').focus();
                return false;
            }
        }
        if (IsStringNullorEmpty($(""#txtAddress"").val())) {
            toastr.warning(""Please Enter Address"");
            return false;
        }
        if ($(""#cboReffferedby"").val() == 0 || $(""#cboReffferedby"").val() == ""0"") {
            toastr.warning(""Please select Refffered By"");
            return false;
        }

    }

    function fnClearPatientRegistrationField");
            WriteLiteral(@"s() {
        $(""#txtFirstName"").val('');
        $(""#txtMiddleName"").val('');
        $(""#txtLastName"").val('');
        $(""#cboGender"").val('0').selectpicker('refresh');
        $(""#txtAge"").val('');
        $(""#dtDob"").val('');
        $(""#txtOccupation"").val('');
        $('#cboMobileNo').val(""0"").selectpicker('refresh');
        $('#txtMobileNo').val('');
        $(""#cboMotherTongue"").val('0').selectpicker('refresh');
        $(""#cboMaritalStatus"").val('0').selectpicker('refresh');
        $(""#cboNationality"").val('0').selectpicker('refresh');
        $(""#cboRelationShip"").val('0').selectpicker('refresh');
        $(""#txtRelationName"").val('');
        $(""#txtNoofChildren"").val('');
        $(""#txtAreaCode"").val('');
        $(""#txtEmailId"").val('');
        $(""#txtAddress"").val('');
        $(""#txtCity"").val('');
        $(""#txtPinCode"").val('');
        $('#cboReffferedby').val(""0"").selectpicker('refresh');
        $(""#txtPresentComplaint"").val('');
        $(""#txtRUHID"").val('')");
            WriteLiteral(@";
        $(""#txtPreExistingHealthCondition"").val('');
        $('input[name=chkComplaintslistitem]').prop('checked', false);

        $('input[name=chkLanguagelistitem]').prop('checked', false);

        $('input[name=txtPersonalInfo]').val('');

        $('input[name=txtPersonalInfo]').attr(""disabled"", true);

        $(""#chkActiveStatus"").parent().addClass(""is-checked"");

        $(""#btnSavePatientRegistration"").attr(""disabled"", false);
        $(""#btnSavePatientRegistration"").html('Save');
    }

    $(""#btnPatientRegistrationCancel"").click(function () {

        fnClearPatientRegistrationFields();
    });

</script>
");
            EndContext();
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<dynamic> Html { get; private set; }
    }
}
#pragma warning restore 1591
