#pragma checksum "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\eSyaNursingStation\Views\OperativeAnaesthesiaCare\V_6004_OT.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "dc4eb8efb734eb8ff57c1997155ccac9c0f0f449"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.Areas_eSyaNursingStation_Views_OperativeAnaesthesiaCare_V_6004_OT), @"mvc.1.0.view", @"/Areas/eSyaNursingStation/Views/OperativeAnaesthesiaCare/V_6004_OT.cshtml")]
[assembly:global::Microsoft.AspNetCore.Mvc.Razor.Compilation.RazorViewAttribute(@"/Areas/eSyaNursingStation/Views/OperativeAnaesthesiaCare/V_6004_OT.cshtml", typeof(AspNetCore.Areas_eSyaNursingStation_Views_OperativeAnaesthesiaCare_V_6004_OT))]
namespace AspNetCore
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"dc4eb8efb734eb8ff57c1997155ccac9c0f0f449", @"/Areas/eSyaNursingStation/Views/OperativeAnaesthesiaCare/V_6004_OT.cshtml")]
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"23ac09be4bcfaa7f9829a01d1a134874eaae1f3b", @"/Areas/eSyaNursingStation/Views/_ViewImports.cshtml")]
    public class Areas_eSyaNursingStation_Views_OperativeAnaesthesiaCare_V_6004_OT : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<dynamic>
    {
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_0 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("href", new global::Microsoft.AspNetCore.Html.HtmlString("~/css/eSyaNursingStation/patientClinicalInformation.css"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_1 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("rel", new global::Microsoft.AspNetCore.Html.HtmlString("stylesheet"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_2 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("src", new global::Microsoft.AspNetCore.Html.HtmlString("~/js/eSyaNursingStation/operativeanaesthesiacare.js"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        #line hidden
        #pragma warning disable 0169
        private string __tagHelperStringValueBuffer;
        #pragma warning restore 0169
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext __tagHelperExecutionContext;
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner __tagHelperRunner = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner();
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __backed__tagHelperScopeManager = null;
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __tagHelperScopeManager
        {
            get
            {
                if (__backed__tagHelperScopeManager == null)
                {
                    __backed__tagHelperScopeManager = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager(StartTagHelperWritingScope, EndTagHelperWritingScope);
                }
                return __backed__tagHelperScopeManager;
            }
        }
        private global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper;
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            BeginContext(0, 2, true);
            WriteLiteral("\r\n");
            EndContext();
#line 2 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\eSyaNursingStation\Views\OperativeAnaesthesiaCare\V_6004_OT.cshtml"
  
    ViewData["Title"] = "Operative Anaesthasic Care";
    Layout = "~/Views/Shared/_Layout.cshtml";

#line default
#line hidden
            BeginContext(111, 4, true);
            WriteLiteral("\r\n\r\n");
            EndContext();
            BeginContext(115, 88, false);
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("link", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.SelfClosing, "dc4eb8efb734eb8ff57c1997155ccac9c0f0f4494810", async() => {
            }
            );
            __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_0);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_1);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            EndContext();
            BeginContext(203, 2, true);
            WriteLiteral("\r\n");
            EndContext();
            DefineSection("scripts", async() => {
                BeginContext(222, 12, true);
                WriteLiteral("\r\n    \r\n    ");
                EndContext();
                BeginContext(234, 75, false);
                __tagHelperExecutionContext = __tagHelperScopeManager.Begin("script", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "dc4eb8efb734eb8ff57c1997155ccac9c0f0f4496249", async() => {
                }
                );
                __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper>();
                __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_2);
                await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
                if (!__tagHelperExecutionContext.Output.IsContentModified)
                {
                    await __tagHelperExecutionContext.SetOutputContentAsync();
                }
                Write(__tagHelperExecutionContext.Output);
                __tagHelperExecutionContext = __tagHelperScopeManager.End();
                EndContext();
                BeginContext(309, 2, true);
                WriteLiteral("\r\n");
                EndContext();
            }
            );
            BeginContext(314, 646, true);
            WriteLiteral(@"


<style>
    /*.ui-jqgrid .ui-jqgrid-bdiv {
        overflow-x: auto;
    }*/
    
    .ui-jqgrid .ui-jqgrid-bdiv {
        /*position: relative;
        margin: 0;
        padding: 0;*/
        overflow: auto;
        text-align: left;
    }

    .ui-state-default ui-th-column-header ui-th-ltr {
        background: #555 !important;
        color: bisque !important;
    }

    .ui-jqgrid .ui-jqgrid-htable th {
        background: #555 !important;
        color: gold !important;
    }

    .jqg-first-row-header {
        visibility: collapse !important;
    }
</style>


<input type=""hidden"" id=""hdIPNumber""");
            EndContext();
            BeginWriteAttribute("value", " value=\"", 960, "\"", 985, 1);
#line 45 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\eSyaNursingStation\Views\OperativeAnaesthesiaCare\V_6004_OT.cshtml"
WriteAttributeValue("", 968, ViewBag.IpNumber, 968, 17, false);

#line default
#line hidden
            EndWriteAttribute();
            BeginContext(986, 37, true);
            WriteLiteral(" />\r\n<input type=\"hidden\" id=\"hdUHID\"");
            EndContext();
            BeginWriteAttribute("value", " value=\"", 1023, "\"", 1044, 1);
#line 46 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\eSyaNursingStation\Views\OperativeAnaesthesiaCare\V_6004_OT.cshtml"
WriteAttributeValue("", 1031, ViewBag.UHID, 1031, 13, false);

#line default
#line hidden
            EndWriteAttribute();
            BeginContext(1045, 46, true);
            WriteLiteral(" />\r\n<input type=\"hidden\" id=\"hdTransactionID\"");
            EndContext();
            BeginWriteAttribute("value", " value=\"", 1091, "\"", 1121, 1);
#line 47 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\eSyaNursingStation\Views\OperativeAnaesthesiaCare\V_6004_OT.cshtml"
WriteAttributeValue("", 1099, ViewBag.TransactionID, 1099, 22, false);

#line default
#line hidden
            EndWriteAttribute();
            BeginContext(1122, 13826, true);
            WriteLiteral(@" />

<div class=""divFixedBar"">
    <div class=""row mr-0"">
        <div class=""col-xl-4 col-lg-6 col-md-6 col-sm-12 col-xs-12 d-flex align-items-center"">
            
            <div>
                <p><span class=""labelname""><i class=""fas fa-chevron-right c-lightgrey""></i> Patient Name</span><span id=""lblPatientName""></span></p>
                <p><span class=""labelname""><i class=""fas fa-chevron-right c-lightgrey""></i> Gender:</span><span id=""lblGender""></span>&nbsp;&nbsp;<span class=""labelname""> Age:</span><span id=""lblAge""></span></p>
            </div>
        </div>
        <div class=""col-xl-4 col-lg-6 col-md-6 col-sm-12 col-xs-12 d-flex align-items-center"">
            
            <div>
                <p><span class=""labelname""><i class=""fas fa-chevron-right c-lightgrey""></i> Doctor Name:</span><span id=""lblConsultantName""></span></p>
                <p><span class=""labelname""><i class=""fas fa-chevron-right c-lightgrey""></i> Room Type:</span> <span id=""lblRoomType""></span>&nbsp;<span ");
            WriteLiteral(@"class=""labelname""> Room No:</span><span id=""lblBedNumber""></span></p>

            </div>
        </div>
        
        <div id=""floatButtons"" class=""col-xl-4 col-lg-12 text-right p-0"">
            <button class=""mdl-button"" id=""btnBackNS"" onclick=""fnBackToNSGrid()""><i class=""fas fa-chevron-left""></i> <span class=""btntext"">Back</span></button>
            <button class=""mdl-button"" id=""btnSaveOperativeAnaesthesicCare"" onclick=""fnSaveOperativeAnaesthesicCare()""><i class=""far fa-save c-green""></i> <span class=""btntext"">Save</span></button>
        </div>
    </div>
</div>

<div class=""row"" style=""margin-right: 0px !important;"">
    <div class=""col-lg-3 col-md-3 col-sm-3 sidebar"" id=""navbar-operativeAnaesthesia"">
        <div class=""sidebar-sticky"">
            <ul class=""nav flex-column"" id=""nav_menu"">
                <li><a href=""#"" id=""v-ot1-tab"" data-bs-toggle=""pill"" data-bs-target=""#v-ot1"" class=""nav-link active"" role=""tab"" aria-controls=""v-ot1"" aria-selected=""true"">Pre Operative Checklist");
            WriteLiteral(@"</a></li>
                <li><a href=""#"" id=""v-ot2-tab"" data-bs-toggle=""pill"" data-bs-target=""#v-ot2"" class=""nav-link"" role=""tab"" aria-controls=""v-ot2"" aria-selected=""true"">Surgical Safety Checklist</a></li>
                <li><a href=""#"" id=""v-ot3-tab"" data-bs-toggle=""pill"" data-bs-target=""#v-ot3"" class=""nav-link"" aria-controls=""v-ot3"" aria-selected=""true"">Pre-Anaesthetic Evaluation</a></li>
                <li><a href=""#"" id=""v-ot4-tab"" data-bs-toggle=""pill"" data-bs-target=""#v-ot4"" class=""nav-link"" aria-controls=""v-ot4"" aria-selected=""true"">Additional Pre-OP Assessment</a></li>
                <li><a href=""#"" id=""v-ot5-tab"" data-bs-toggle=""pill"" data-bs-target=""#v-ot5"" class=""nav-link"" aria-controls=""v-ot5"" aria-selected=""true"">Immediate Pre-Operative Re-Evaluation</a></li>
                <li><a href=""#"" id=""v-ot6-tab"" data-bs-toggle=""pill"" data-bs-target=""#v-ot6"" class=""nav-link"" aria-controls=""v-ot6"" aria-selected=""true"">Aneasthesia Record</a></li>
                <li><a href=""#"" id=""v-ot7-tab"" d");
            WriteLiteral(@"ata-bs-toggle=""pill"" data-bs-target=""#v-ot7"" class=""nav-link"" aria-controls=""v-ot7"">Surgeons Notes</a></li>
                <li><a href=""#"" id=""v-ot8-tab"" data-bs-toggle=""pill"" data-bs-target=""#v-ot8"" class=""nav-link"" aria-controls=""v-ot8"">Intra Operative Nursing Record</a></li>
                <li><a href=""#"" id=""v-ot9-tab"" data-bs-toggle=""pill"" data-bs-target=""#v-ot9"" class=""nav-link"" aria-controls=""v-ot9"">Recovery Room Record</a></li>
                <li><a href=""#"" id=""v-ot10-tab"" data-bs-toggle=""pill"" data-bs-target=""#v-ot10"" class=""nav-link"" aria-controls=""v-ot10"">Post-Operative Instructions</a></li>
                <li><a href=""#"" id=""v-ot11-tab"" data-bs-toggle=""pill"" data-bs-target=""#v-ot11"" class=""nav-link"" aria-controls=""v-ot11"">Post-Anaesthesia Care</a></li>
            </ul>
        </div>
    </div>
    <div class="""" id=""mainContent"">
        <div class=""tab-content"" id=""v-pills-tabContent"">

            <div class=""tab-pane fade show active"" id=""v-ot1"" role=""tabpanel"" aria-labelledby=");
            WriteLiteral(@"""v-ot1-tab"">
                <div class=""row"">
                    <div class=""col-12 p-0"">
                        <h6 class=""main-heading""><i class=""fa fa-bars mr-10""></i>Pre Operative Checklist</h6>
                    </div>
                </div>
                <div class=""row mr-0"" style=""margin-right:0px;"">
                    <div class=""col-lg-12 col-md-12 col-sm-12 mb-2 divNursingCarePlan"">
                        <div id=""dvPreOperativeChecklistTemplate""></div>
                    </div>
                </div>
            </div>

            <div class=""tab-pane fade"" id=""v-ot2"" role=""tabpanel"" aria-labelledby=""v-ot2-tab"">
                <div class=""row"">
                    <div class=""col-12 p-0"">
                        <h6 class=""main-heading""><i class=""fa fa-bars mr-10""></i>Surgical Safety Checklist</h6>
                    </div>
                </div>
                <div class=""row mr-0"" style=""margin-right:0px;"">
                    <div class=""col-lg-12 col-md-12 col");
            WriteLiteral(@"-sm-12"" style=""padding-right:0px"">
                        <div id=""dvSurgicalSafetyTemplate""></div>
                    </div>
                </div>
            </div>

            <div class=""tab-pane fade"" id=""v-ot3"" role=""tabpanel"" aria-labelledby=""v-ot3-tab"">
                <div class=""row"">
                    <div class=""col-12 p-0"">
                        <h6 class=""main-heading""><i class=""fa fa-bars mr-10""></i>Pre-Anaesthetic Evaluation</h6>
                    </div>
                </div>
                <div class=""row mr-0"" style=""margin-right:0px;"">
                    <div class=""col-lg-12 col-md-12 col-sm-12"" style=""padding-right:0px"">
                        <div id=""dvPreAnaestheticEvaluationTemplate""></div>
                    </div>
                </div>
            </div>

            <div class=""tab-pane fade"" id=""v-ot4"" role=""tabpanel"" aria-labelledby=""v-ot4-tab"">
                <div class=""row"">
                    <div class=""col-12 p-0"">
                   ");
            WriteLiteral(@"     <h6 class=""main-heading""><i class=""fa fa-bars mr-10""></i>Additional Pre-OP Assessment</h6>
                    </div>
                </div>
                <div class=""row mr-0"" style=""margin-right:0px;"">
                    <div class=""col-lg-12 col-md-12 col-sm-12"" style=""padding-right:0px"">
                        <div id=""dvAdditionalPreOPAssessmentTemplate""></div>
                    </div>
                </div>
            </div>

            <div class=""tab-pane fade"" id=""v-ot5"" role=""tabpanel"" aria-labelledby=""v-ot5-tab"">
                <div class=""row"">
                    <div class=""col-12 p-0"">
                        <h6 class=""main-heading""><i class=""fa fa-bars mr-10""></i>Immediate Pre-Operative Re-Evaluation</h6>
                    </div>
                </div>
                <div class=""row mr-0"" style=""margin-right:0px;"">
                    <div class=""col-lg-12 col-md-12 col-sm-12"" style=""padding-right:0px"">
                        <div id=""dvImmediatePreOperativ");
            WriteLiteral(@"ePreEvaluationTemplate""></div>
                    </div>
                </div>
            </div>

            <div class=""tab-pane fade"" id=""v-ot6"" role=""tabpanel"" aria-labelledby=""v-ot6-tab"">
                <div class=""row"">
                    <div class=""col-12 p-0"">
                        <h6 class=""main-heading""><i class=""fa fa-bars mr-10""></i>Aneasthesia Record</h6>
                    </div>
                </div>
                <div class=""row mr-0"" style=""margin-right:0px;"">
                    <div class=""col-lg-12 col-md-12 col-sm-12"" style=""padding-right:0px"">
                        <div id=""dvAneasthesiaRecordTemplate""></div>
                    </div>
                </div>
            </div>

            <div class=""tab-pane fade"" id=""v-ot7"" role=""tabpanel"" aria-labelledby=""v-ot7-tab"">
                <div class=""row"">
                    <div class=""col-12 p-0"">
                        <h6 class=""main-heading""><i class=""fa fa-bars mr-10""></i>Surgeons Notes</h6>
   ");
            WriteLiteral(@"                 </div>
                </div>
                <div class=""row mr-0"" style=""margin-right:0px;"">
                    <div class=""col-lg-12 col-md-12 col-sm-12"" style=""padding-right:0px"">
                        <div id=""dvSurgeonsNotesTemplate""></div>
                    </div>
                </div>
            </div>

            <div class=""tab-pane fade"" id=""v-ot8"" role=""tabpanel"" aria-labelledby=""v-ot8-tab"">
                <div class=""row"">
                    <div class=""col-12 p-0"">
                        <h6 class=""main-heading""><i class=""fa fa-bars mr-10""></i>Intra Operative Nursing Record</h6>
                    </div>
                </div>
                <div class=""row mr-0"" style=""margin-right:0px;"">
                    <div class=""col-lg-12 col-md-12 col-sm-12"" style=""padding-right:0px;width:2000px;overflow:auto;"">
                        <div id=""dvIntraOperativeNursingTemplate""></div>
                    </div>
                </div>
            </div>
");
            WriteLiteral(@"
            <div class=""tab-pane fade"" id=""v-ot9"" role=""tabpanel"" aria-labelledby=""v-ot9-tab"">
                <div class=""row"">
                    <div class=""col-12 p-0"">
                        <h6 class=""main-heading""><i class=""fa fa-bars mr-10""></i>Recovery Room Record</h6>
                    </div>
                </div>
                <div class=""row mr-0"" style=""margin-right:0px;"">
                    <div class=""col-lg-12 col-md-12 col-sm-12"" style=""padding-right:0px"">
                        <div id=""dvRecoveryRoomTemplate""></div>
                    </div>
                </div>
            </div>

            <div class=""tab-pane fade"" id=""v-ot10"" role=""tabpanel"" aria-labelledby=""v-ot10-tab"">
                <div class=""row"">
                    <div class=""col-12 p-0"">
                        <h6 class=""main-heading""><i class=""fa fa-bars mr-10""></i>Post-Operative Instructions</h6>
                    </div>
                </div>
                <div class=""row mr-0"" style");
            WriteLiteral(@"=""margin-right:0px;"">
                    <div class=""col-lg-12 col-md-12 col-sm-12"" style=""padding-right:0px;width:2000px;overflow:auto;"">
                        <div id=""dvPostOpeativeInstructionsTemplate""></div>
                    </div>
                </div>
            </div>

            <div class=""tab-pane fade"" id=""v-ot11"" role=""tabpanel"" aria-labelledby=""v-ot11-tab"">
                <div class=""row"">
                    <div class=""col-12 p-0"">
                        <h6 class=""main-heading""><i class=""fa fa-bars mr-10""></i>Post-Anaesthesia Care</h6>
                    </div>
                </div>
                <div class=""row mr-0"" style=""margin-right:0px;"">
                    <div class=""col-lg-12 col-md-12 col-sm-12"" style=""padding-right:0px;width:2000px;overflow:auto;"">
                        <div id=""dvPostAnaesthesiaCaresTemplate""></div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>


<div class=""modal f");
            WriteLiteral(@"ade in"" id=""PopupAneasthesiaRecord"" data-keyboard=""false"" data-backdrop=""static"">
    <div class=""modal-dialog modal-lg"" role=""document"" style=""box-shadow:none;"">
        <div class=""modal-content"">
            <div class=""modal-header popupHeader"">
                <button type=""button"" class=""close ml-auto"" data-dismiss=""modal""> <i class=""fa fa-times""></i></button>
                <h4 class=""modal-title"">Aneasthesia Record</h4>
            </div>

            <div class=""modal-body"">
                <div class=""row"">
                    <div class=""col-sm-6"">
                        <div class=""form-group"">
                            <label>Date</label>
                            <input class=""form-control datepicker"" type=""text"" maxlength=""8"" id=""dpAneasthesiaRecordDate"" />
                        </div>
                    </div>
                    <div class=""col-sm-6"">
                        <div class=""form-group"">
                            <label>Time</label>
                  ");
            WriteLiteral(@"          <input class=""form-control timepicker"" type=""time"" maxlength=""8"" id=""tpAneasthesiaRecordTime"" />
                        </div>
                    </div>
                </div>
                <div id=""dvAneasthesiaRecordTemplate""></div>
            </div>
            <div class=""modal-footer"">
                <div class=""row"">
                    <div class=""col-lg-12"">
                        <button class=""mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent primary-button""
                                id=""btnSaveVitalCharts"" onclick=""saveAneasthesiaRecord()"">
                            <i class=""fa fa-save""></i> Save
                        </button>
                        <button class=""mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect  cancel-button cancel-button"" data-dismiss=""modal""><i class=""fa fa-times""></i> Cancel </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
<");
            WriteLiteral(@"/div>

<script>

    $("".nav li a"").click(function () {
        $("".nav li a"").removeClass(""active"");
        $(this).addClass(""active"");
        $('.tab-pane').removeClass('show active');
        var v = $(this).attr('data-bs-target'); console.log(v);
        $(v).addClass('show active');
    });

    $(document).ready(function () {
    });
    function fnBackToNSGrid() {
        window.location.href = getBaseURL() + ""/eSyaNursingStation/OperativeAnaesthesiaCare/V_6004_00"";
    }

</script>");
            EndContext();
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<dynamic> Html { get; private set; }
    }
}
#pragma warning restore 1591
