#pragma checksum "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\Configure\Views\FormNames\ECA_01_00.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "5d880b3cb23d8fc7bf2c692a86c49143bb6721ec"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.Areas_Configure_Views_FormNames_ECA_01_00), @"mvc.1.0.view", @"/Areas/Configure/Views/FormNames/ECA_01_00.cshtml")]
[assembly:global::Microsoft.AspNetCore.Mvc.Razor.Compilation.RazorViewAttribute(@"/Areas/Configure/Views/FormNames/ECA_01_00.cshtml", typeof(AspNetCore.Areas_Configure_Views_FormNames_ECA_01_00))]
namespace AspNetCore
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
#line 1 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\Configure\Views\FormNames\ECA_01_00.cshtml"
using Microsoft.AspNetCore.Mvc.Localization;

#line default
#line hidden
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"5d880b3cb23d8fc7bf2c692a86c49143bb6721ec", @"/Areas/Configure/Views/FormNames/ECA_01_00.cshtml")]
    public class Areas_Configure_Views_FormNames_ECA_01_00 : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<dynamic>
    {
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_0 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("rel", new global::Microsoft.AspNetCore.Html.HtmlString("stylesheet"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_1 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("href", new global::Microsoft.AspNetCore.Html.HtmlString("~/css/jsTree.css"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_2 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("src", new global::Microsoft.AspNetCore.Html.HtmlString("~/js/jsTree.js"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_3 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("href", new global::Microsoft.AspNetCore.Html.HtmlString("~/css/listswap.css"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_4 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("src", new global::Microsoft.AspNetCore.Html.HtmlString("~/js/jquery.listswap.js"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_5 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("src", new global::Microsoft.AspNetCore.Html.HtmlString("~/js/Config/FormsMenu.js"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        #line hidden
        #pragma warning disable 0169
        private string __tagHelperStringValueBuffer;
        #pragma warning restore 0169
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext __tagHelperExecutionContext;
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner __tagHelperRunner = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner();
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __backed__tagHelperScopeManager = null;
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __tagHelperScopeManager
        {
            get
            {
                if (__backed__tagHelperScopeManager == null)
                {
                    __backed__tagHelperScopeManager = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager(StartTagHelperWritingScope, EndTagHelperWritingScope);
                }
                return __backed__tagHelperScopeManager;
            }
        }
        private global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper;
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            BeginContext(46, 2, true);
            WriteLiteral("\r\n");
            EndContext();
            BeginContext(82, 2, true);
            WriteLiteral("\r\n");
            EndContext();
#line 5 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\Configure\Views\FormNames\ECA_01_00.cshtml"
  
    ViewData["Title"] = "Forms";
    Layout = "~/Views/Shared/_Layout.cshtml";

#line default
#line hidden
#line 9 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\Configure\Views\FormNames\ECA_01_00.cshtml"
  
    var userFormRole = (eSyaEnterprise_UI.Models.DO_UserFormRole)ViewBag.UserFormRole;

#line default
#line hidden
            BeginContext(267, 46, true);
            WriteLiteral("<script>\r\n    var _userFormRole = JSON.parse(\'");
            EndContext();
            BeginContext(314, 38, false);
#line 13 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\Configure\Views\FormNames\ECA_01_00.cshtml"
                               Write(Html.Raw(Json.Serialize(userFormRole)));

#line default
#line hidden
            EndContext();
            BeginContext(352, 1330, true);
            WriteLiteral(@"');
</script>

<style>
    .popover-header {
        margin-top: 0px;
        line-height: 30px;
        padding-top: 0.15rem;
    }

    .popover {
        transform: translate3d(184px, 518px, 0px);
        max-width: 400px;
        height: 200px;
        overflow-y: auto;
    }

    .ui-jqgrid .ui-jqgrid-bdiv {
        position: relative;
        margin: 0em;
        padding: 0;
        /*overflow: auto;*/
        overflow-x: hidden;
        overflow-y: auto;
        text-align: left;
    }

    .mdl-card__supporting-text {
        padding: 8px 8px 4px !important;
    }
</style>



<div class=""row row-bottom-pad"">
    <div class=""col-sm-12 col-md-4 col-lg-4"">
        <div id=""FormMasterTree"">
        </div>
    </div>

    <div id=""dvForm"" class=""col-lg-8 col-md-8 col-sm-12"">

        <div class=""demo-card-square mdl-card mdl-shadow--2dp marbot15 fullwidth"" id=""pnlAddForms"">
            <div class=""mdl-card__title mdl-card--expand padleft0 padtop0 d-block"">
      ");
            WriteLiteral(@"          <h5 class=""mdl-card__title-text""> eSya Forms </h5>
            </div>
            <div class=""mdl-card__supporting-text fullwidth"">
                <div class=""row"" id=""dvNavigateURL"">
                    <div class=""col-sm-12 col-md-12 col-lg-4 form-group"">
                        <label> ");
            EndContext();
            BeginContext(1683, 27, false);
#line 62 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\Configure\Views\FormNames\ECA_01_00.cshtml"
                           Write(Localizer["ControllerName"]);

#line default
#line hidden
            EndContext();
            BeginContext(1710, 249, true);
            WriteLiteral(" </label>\r\n                        <select class=\"selectpicker\" data-live-search=\"true\" id=\"cboAreaController\" title=\"\" data-size=\"5\" onchange=\"fnController_onChanged()\">\r\n                            <option value=\"0\"> Choose a controller</option>\r\n");
            EndContext();
#line 65 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\Configure\Views\FormNames\ECA_01_00.cshtml"
                             if (ViewBag.AreaController != null)
                            {
                                foreach (var code in ViewBag.AreaController)
                                {

#line default
#line hidden
            BeginContext(2169, 43, true);
            WriteLiteral("                                    <option");
            EndContext();
            BeginWriteAttribute("value", " value=\"", 2212, "\"", 2247, 3);
#line 69 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\Configure\Views\FormNames\ECA_01_00.cshtml"
WriteAttributeValue("", 2220, code.Area, 2220, 10, false);

#line default
#line hidden
            WriteAttributeValue("", 2230, "/", 2230, 1, true);
#line 69 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\Configure\Views\FormNames\ECA_01_00.cshtml"
WriteAttributeValue("", 2231, code.Controller, 2231, 16, false);

#line default
#line hidden
            EndWriteAttribute();
            BeginContext(2248, 1, true);
            WriteLiteral(">");
            EndContext();
            BeginContext(2250, 9, false);
#line 69 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\Configure\Views\FormNames\ECA_01_00.cshtml"
                                                                           Write(code.Area);

#line default
#line hidden
            EndContext();
            BeginContext(2259, 1, true);
            WriteLiteral("/");
            EndContext();
            BeginContext(2261, 15, false);
#line 69 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\Configure\Views\FormNames\ECA_01_00.cshtml"
                                                                                      Write(code.Controller);

#line default
#line hidden
            EndContext();
            BeginContext(2276, 11, true);
            WriteLiteral("</option>\r\n");
            EndContext();
#line 70 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\Configure\Views\FormNames\ECA_01_00.cshtml"
                                }
                            }

#line default
#line hidden
            BeginContext(2353, 236, true);
            WriteLiteral("                        </select>\r\n                    </div>\r\n                </div>\r\n                <div class=\"row\">\r\n                    <div class=\"col-sm-12 col-md-12 col-lg-4 form-group\" hidden>\r\n                        <label> ");
            EndContext();
            BeginContext(2590, 19, false);
#line 77 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\Configure\Views\FormNames\ECA_01_00.cshtml"
                           Write(Localizer["FormID"]);

#line default
#line hidden
            EndContext();
            BeginContext(2609, 254, true);
            WriteLiteral(" </label>\r\n                        <input type=\"text\" name=\"int\" class=\"form-control integerFormat\" id=\"txtFormID\" />\r\n                    </div>\r\n                    <div class=\"col-sm-12 col-md-12 col-lg-4 form-group\">\r\n                        <label> ");
            EndContext();
            BeginContext(2864, 21, false);
#line 81 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\Configure\Views\FormNames\ECA_01_00.cshtml"
                           Write(Localizer["FormCode"]);

#line default
#line hidden
            EndContext();
            BeginContext(2885, 233, true);
            WriteLiteral(" </label>\r\n                        <input type=\"text\" class=\"form-control \" id=\"txtFormCode\" />\r\n                    </div>\r\n                    <div class=\"col-sm-12 col-md-12 col-lg-8 form-group\">\r\n                        <label>  ");
            EndContext();
            BeginContext(3119, 21, false);
#line 85 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\Configure\Views\FormNames\ECA_01_00.cshtml"
                            Write(Localizer["FormDesc"]);

#line default
#line hidden
            EndContext();
            BeginContext(3140, 320, true);
            WriteLiteral(@" </label>
                        <input type=""text"" class=""form-control "" id=""txtFormDescription"" />
                    </div>
                </div>
                <div class=""row"" style=""display:none"">
                    <div class=""col-sm-12 col-md-12 col-lg-12 form-group"">
                        <label> ");
            EndContext();
            BeginContext(3461, 27, false);
#line 91 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\Configure\Views\FormNames\ECA_01_00.cshtml"
                           Write(Localizer["ControllerName"]);

#line default
#line hidden
            EndContext();
            BeginContext(3488, 310, true);
            WriteLiteral(@"</label>
                        <input id=""txtControllerName"" class=""form-control"" maxlength=""100"" type=""text"" readonly />
                    </div>
                </div>
                <div class=""row"">
                    <div class=""col-sm-12 col-md-12 col-lg-12"">
                        <label> ");
            EndContext();
            BeginContext(3799, 20, false);
#line 97 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\Configure\Views\FormNames\ECA_01_00.cshtml"
                           Write(Localizer["ToolTip"]);

#line default
#line hidden
            EndContext();
            BeginContext(3819, 162, true);
            WriteLiteral("</label>\r\n                        <input id=\"txtToolTip\" class=\"form-control\" maxlength=\"100\" type=\"text\" />\r\n                    </div>\r\n                </div>\r\n");
            EndContext();
            BeginContext(5602, 289, true);
            WriteLiteral(@"
                <div class=""mdl-card__actions text-center pad0 m-t-4"">

                    <button type=""button"" class=""mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect m-r-15 mdl-js-ripple-effect"" id=""btnFMAdd"" onclick=""fnSaveFormMaster()""><i class=""fa fa-plus""></i> ");
            EndContext();
            BeginContext(5892, 16, false);
#line 127 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\Configure\Views\FormNames\ECA_01_00.cshtml"
                                                                                                                                                                                                                Write(Localizer["Add"]);

#line default
#line hidden
            EndContext();
            BeginContext(5908, 210, true);
            WriteLiteral(" </button>\r\n                    <button type=\"button\" class=\"mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect\" id=\"btnConfigureMenu\" onclick=\"fnOpenConfigureMenu()\" )><i class=\"fa fa-plus\"></i> ");
            EndContext();
            BeginContext(6119, 26, false);
#line 128 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\Configure\Views\FormNames\ECA_01_00.cshtml"
                                                                                                                                                                                                 Write(Localizer["ConfigureMenu"]);

#line default
#line hidden
            EndContext();
            BeginContext(6145, 786, true);
            WriteLiteral(@"</button>
                </div>

                <div class=""col-lg-12 col-md-12 col-sm-12 pad0 p-b-4 m-y-4"">
                    <table id=""jqgInternalForms""></table>
                    <div id=""jqpInternalForms""></div>
                </div>

                <div id=""dvFormAction"">
                    <div class=""col-lg-12 col-md-12 col-sm-12 pad0"">
                        <table id=""jqgFormAction""></table>
                        <div id=""jqpFormAction""></div>
                    </div>

                    <div class=""mdl-card__actions text-center m-t-4 pad0"">
                        <button type=""button"" class=""mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect"" id=""btnSaveFormAction"" onclick=""fnSaveFormAction()""><i class=""fa fa-save""></i> ");
            EndContext();
            BeginContext(6932, 23, false);
#line 143 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\Configure\Views\FormNames\ECA_01_00.cshtml"
                                                                                                                                                                                                 Write(Localizer["SaveAction"]);

#line default
#line hidden
            EndContext();
            BeginContext(6955, 190, true);
            WriteLiteral(" </button>\r\n                    </div>\r\n                </div>\r\n                <div class=\"row  m-t-4\" id=\"dvFormParameter\">\r\n                    <div class=\"col-sm-12 col-md-6 col-lg-6\">\r\n");
            EndContext();
            BeginContext(7250, 454, true);
            WriteLiteral(@"                        <table id=""jqgFormParameter""></table>
                        <div id=""jqpFormParameter""></div>
                        <div style=""text-align:center;padding:5px"">
                            <button class=""mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent primary-button"" id=""btnSaveFormParameter"" onclick=""fnSaveFormParameter();"">
                                <i class=""fa fa-save""></i> ");
            EndContext();
            BeginContext(7705, 17, false);
#line 153 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\Configure\Views\FormNames\ECA_01_00.cshtml"
                                                      Write(Localizer["Save"]);

#line default
#line hidden
            EndContext();
            BeginContext(7722, 643, true);
            WriteLiteral(@"
                            </button>
                        </div>
                    </div>
                    <div class=""col-sm-12 col-md-6 col-lg-6"" id=""dvTable"">
                        <table id=""jqgFormSubParameter""></table>
                        <div id=""jqpFormSubParameter""></div>
                        <div style=""text-align:center;padding:5px"">
                            <button class=""mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent primary-button"" id=""btnSaveFormSubParameter"" onclick=""fnSaveFormSubParameter();"">
                                <i class=""fa fa-save""></i> ");
            EndContext();
            BeginContext(8366, 17, false);
#line 162 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\Configure\Views\FormNames\ECA_01_00.cshtml"
                                                      Write(Localizer["Save"]);

#line default
#line hidden
            EndContext();
            BeginContext(8383, 101, true);
            WriteLiteral("\r\n                            </button>\r\n                        </div>\r\n                    </div>\r\n");
            EndContext();
            BeginContext(8584, 4, true);
            WriteLiteral("\r\n\r\n");
            EndContext();
            BeginContext(8947, 516, true);
            WriteLiteral(@"                </div>


            </div>
        </div>
    </div>
</div>

<div class=""modal fade in"" id=""PopupSubParameter"" data-keyboard=""false"" data-backdrop=""static"">
    <div class=""modal-dialog modal-md "" role=""document"" style=""box-shadow:none;"">
        <div class=""modal-content "">
            <div class=""modal-header popupHeader"">
                <button type=""button"" class=""close ml-auto"" data-dismiss=""modal""> <i class=""fa fa-times""></i></button>
                <h4 class=""modal-title"">");
            EndContext();
            BeginContext(9464, 27, false);
#line 185 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\Configure\Views\FormNames\ECA_01_00.cshtml"
                                   Write(Localizer["Form Parameter"]);

#line default
#line hidden
            EndContext();
            BeginContext(9491, 750, true);
            WriteLiteral(@"</h4>
            </div>

            <div class=""modal-body"">
                <div class=""row"">
                    <div class=""col-md-12 col-sm-12 col-lg-12"">
                        <table id=""jqgFormSubParameter1""></table>
                        <div id=""jqpFormSubParameter1""></div>
                    </div>
                </div>
            </div>
            <div class=""modal-footer"">
                <div class=""row"">
                    <div class=""col-lg-12"">
                        <button class=""mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent primary-button"" id=""btnSaveFormSubParameter"" onclick=""fnSaveFormSubParameter();"">
                            <i class=""fa fa-save""></i> ");
            EndContext();
            BeginContext(10242, 17, false);
#line 200 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\Configure\Views\FormNames\ECA_01_00.cshtml"
                                                  Write(Localizer["Save"]);

#line default
#line hidden
            EndContext();
            BeginContext(10259, 249, true);
            WriteLiteral("\r\n                        </button>\r\n                        <button class=\"mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect  cancel-button cancel-button\" data-dismiss=\"modal\" id=\"btnSaveFormSubParameter\"><i class=\"fa fa-times\"></i> ");
            EndContext();
            BeginContext(10509, 19, false);
#line 202 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\Configure\Views\FormNames\ECA_01_00.cshtml"
                                                                                                                                                                                                               Write(Localizer["Cancel"]);

#line default
#line hidden
            EndContext();
            BeginContext(10528, 732, true);
            WriteLiteral(@" </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<div class=""row"">
    <div class=""col-sm-4 col-lg-4 col-md-4"">
        <span class=""highlight""></span><span class=""bar""></span>
        <div class=""modal fade in"" id=""popupUserAction"" data-keyboard=""false"" data-backdrop=""static"">
            <div class=""modal-dialog modal-lg  "" role=""document"" style=""box-shadow:none;"">
                <div class=""modal-content "">
                    <div class=""modal-header popupHeader"">
                        <button type=""button"" class=""close ml-auto"" data-dismiss=""modal""> <i class=""fa fa-times""></i></button>
                        <h4 class=""modal-title"">");
            EndContext();
            BeginContext(11261, 23, false);
#line 219 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\Configure\Views\FormNames\ECA_01_00.cshtml"
                                           Write(Localizer["UserAction"]);

#line default
#line hidden
            EndContext();
            BeginContext(11284, 1416, true);
            WriteLiteral(@"</h4>
                    </div>
                    <div class=""err_div_mar animated fadeInUp"" id=""errpopUP"" style=""display:none"">
                        <p class=""errorMsg_p"" id=""errmsg""></p>
                        <p class=""succMsg_p"" id=""succmsg""></p>
                    </div>

                    <div class=""modal-body"">
                        <div class=""row"">
                            <div class=""col-md-12 col-sm-12 col-lg-12"">
                                <div class=""row"" id=""lbxUserAction"">
                                </div>
                            </div>
                        </div>

                    </div>

                    <div class=""modal-footer"">
                        <div class=""row"">
                            <div class=""col-lg-12"">
                                <button class=""mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent primary-button"" onclick=""return fnAddUserAction_onclick();""> Save </button>

     ");
            WriteLiteral(@"                           <button class=""mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect  cancel-button cancel-button"" data-dismiss=""modal""> Cancel</button>

                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class=""clearfix""></div>
</div>

");
            EndContext();
            DefineSection("scripts", async() => {
                BeginContext(12717, 6, true);
                WriteLiteral("\r\n    ");
                EndContext();
                BeginContext(12723, 49, false);
                __tagHelperExecutionContext = __tagHelperScopeManager.Begin("link", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.SelfClosing, "5d880b3cb23d8fc7bf2c692a86c49143bb6721ec26007", async() => {
                }
                );
                __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper>();
                __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_0);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_1);
                await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
                if (!__tagHelperExecutionContext.Output.IsContentModified)
                {
                    await __tagHelperExecutionContext.SetOutputContentAsync();
                }
                Write(__tagHelperExecutionContext.Output);
                __tagHelperExecutionContext = __tagHelperScopeManager.End();
                EndContext();
                BeginContext(12772, 6, true);
                WriteLiteral("\r\n    ");
                EndContext();
                BeginContext(12778, 38, false);
                __tagHelperExecutionContext = __tagHelperScopeManager.Begin("script", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "5d880b3cb23d8fc7bf2c692a86c49143bb6721ec27344", async() => {
                }
                );
                __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper>();
                __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_2);
                await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
                if (!__tagHelperExecutionContext.Output.IsContentModified)
                {
                    await __tagHelperExecutionContext.SetOutputContentAsync();
                }
                Write(__tagHelperExecutionContext.Output);
                __tagHelperExecutionContext = __tagHelperScopeManager.End();
                EndContext();
                BeginContext(12816, 8, true);
                WriteLiteral("\r\n\r\n    ");
                EndContext();
                BeginContext(12824, 51, false);
                __tagHelperExecutionContext = __tagHelperScopeManager.Begin("link", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.SelfClosing, "5d880b3cb23d8fc7bf2c692a86c49143bb6721ec28606", async() => {
                }
                );
                __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper>();
                __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_3);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_0);
                await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
                if (!__tagHelperExecutionContext.Output.IsContentModified)
                {
                    await __tagHelperExecutionContext.SetOutputContentAsync();
                }
                Write(__tagHelperExecutionContext.Output);
                __tagHelperExecutionContext = __tagHelperScopeManager.End();
                EndContext();
                BeginContext(12875, 6, true);
                WriteLiteral("\r\n    ");
                EndContext();
                BeginContext(12881, 47, false);
                __tagHelperExecutionContext = __tagHelperScopeManager.Begin("script", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "5d880b3cb23d8fc7bf2c692a86c49143bb6721ec29943", async() => {
                }
                );
                __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper>();
                __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_4);
                await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
                if (!__tagHelperExecutionContext.Output.IsContentModified)
                {
                    await __tagHelperExecutionContext.SetOutputContentAsync();
                }
                Write(__tagHelperExecutionContext.Output);
                __tagHelperExecutionContext = __tagHelperScopeManager.End();
                EndContext();
                BeginContext(12928, 8, true);
                WriteLiteral("\r\n\r\n    ");
                EndContext();
                BeginContext(12936, 48, false);
                __tagHelperExecutionContext = __tagHelperScopeManager.Begin("script", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "5d880b3cb23d8fc7bf2c692a86c49143bb6721ec31205", async() => {
                }
                );
                __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper>();
                __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_5);
                await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
                if (!__tagHelperExecutionContext.Output.IsContentModified)
                {
                    await __tagHelperExecutionContext.SetOutputContentAsync();
                }
                Write(__tagHelperExecutionContext.Output);
                __tagHelperExecutionContext = __tagHelperScopeManager.End();
                EndContext();
                BeginContext(12984, 2, true);
                WriteLiteral("\r\n");
                EndContext();
            }
            );
            BeginContext(12989, 58, true);
            WriteLiteral("\r\n<script>\r\n\r\n    var localization = {\r\n        AddForm: \'");
            EndContext();
            BeginContext(13048, 20, false);
#line 267 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\Configure\Views\FormNames\ECA_01_00.cshtml"
             Write(Localizer["AddForm"]);

#line default
#line hidden
            EndContext();
            BeginContext(13068, 21, true);
            WriteLiteral("\',\r\n        FormID: \'");
            EndContext();
            BeginContext(13090, 19, false);
#line 268 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\Configure\Views\FormNames\ECA_01_00.cshtml"
            Write(Localizer["FormID"]);

#line default
#line hidden
            EndContext();
            BeginContext(13109, 3191, true);
            WriteLiteral(@"',

    };

    var prevSelectedID = 'FM';

    $(function () {

        $('#dvTable').hide();
        $('#dvFormAction').hide();
        $('#dvFormParameter').hide();
        fnLoadFormsTree();
         fnTreeSize(""#FormMasterTree"");


        $(window).on('resize', function () {
            fnTreeSize(""#FormMasterTree"");

        });
        $(""#cboAreaController"").val("""");
        $('#cboAreaController').selectpicker('refresh');
        $(""#txtFormID"").val('');
        $(""#txtFormCode"").val('');
        $(""#txtFormDescription"").val('');
        $(""#txtControllerName"").val('');
        //$('#chkIsDocumentNoRequired').parent().removeClass(""is-checked"");
        //$('#chkIsStoreLink').parent().removeClass(""is-checked"");
        //$('#chkIsDoctor').parent().removeClass(""is-checked"");

        var winW = $(window).width();
        var winH = $(window).height();
            if (winW < 768) {

        }
        console.log(winW);


    });

    function fnEditFormSize() {
 ");
            WriteLiteral(@"       $("".mdl-card__supporting-text"").css({
            'max-height': $(window).innerHeight() - 203,
            'overflow': 'auto !important'
        });

    }

    function fnController_onChanged() {
        $(""#txtControllerName"").val($('#cboAreaController').val());
    }

    //Tree Root Label is clicked
    $(""#lblFormDetail"").click(function () {

        $(""#cboAreaController"").val("""");
        $('#cboAreaController').selectpicker('refresh');
        $(""#txtFormID"").val('');
        $(""#txtFormCode"").val('');
        $(""#txtFormDescription"").val('');
        $(""#txtControllerName"").val('');
        $(""#txtToolTip"").val('');
        //$('#chkIsDocumentNoRequired').parent().removeClass(""is-checked"");
        //$('#chkIsStoreLink').parent().removeClass(""is-checked"");
        //$('#chkIsDoctor').parent().removeClass(""is-checked"");
        $('#dvFormParameter').hide();
       // eSyaParams.ClearValue();

    })

    function fnLoadFormsTree() {

        $.ajax({
            ");
            WriteLiteral(@"url: getBaseURL() + '/FormNames/GetFormList',
            type: 'POST',
            datatype: 'json',
            contentType: 'application/json; charset=utf-8',
            async: false,
            success: function (result) {
                $(""#FormMasterTree"").jstree({ core: { data: result, multiple: false } });
            },
            error: function (error) {
                toastr.error(error.statusText)
            }
        });

        $(""#FormMasterTree"").on('loaded.jstree', function () {
            $(""#FormMasterTree"").jstree()._open_to(prevSelectedID);
            $('#FormMasterTree').jstree().select_node(prevSelectedID);
        });

        $('#FormMasterTree').on(""changed.jstree"", function (e, data) {
            if (data.node != undefined) {
                prevSelectedID = data.node.id;

                var parentNode = $(""#FormMasterTree"").jstree(true).get_parent(data.node.id);

                var formID = prevSelectedID;

                // If Parent node is");
            WriteLiteral(" selected\r\n                if (parentNode == \"#\") {\r\n                    $(\"#pnlAddForms .mdl-card__title-text\").text(\"");
            EndContext();
            BeginContext(16301, 20, false);
#line 368 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\Configure\Views\FormNames\ECA_01_00.cshtml"
                                                             Write(Localizer["AddForm"]);

#line default
#line hidden
            EndContext();
            BeginContext(16321, 601, true);
            WriteLiteral(@""");
                    $(""#cboAreaController"").val("""");
                    $('#cboAreaController').selectpicker('refresh');
                    $(""#txtFormDescription"").val('');
                    $(""#txtControllerName"").val('');
                    $(""#txtToolTip"").val('');
                    //$('#chkIsDocumentNoRequired').parent().removeClass(""is-checked"");
                    //$('#chkIsStoreLink').parent().removeClass(""is-checked"");
                    //$('#chkIsDoctor').parent().removeClass(""is-checked"");

                    $(""#btnFMAdd"").html(""<i class='fa fa-plus'></i> ");
            EndContext();
            BeginContext(16923, 16, false);
#line 378 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\Configure\Views\FormNames\ECA_01_00.cshtml"
                                                               Write(Localizer["Add"]);

#line default
#line hidden
            EndContext();
            BeginContext(16939, 893, true);
            WriteLiteral(@""");

                    $(""#btnFMAdd"").attr(""disabled"", _userFormRole.IsInsert === false);
                    $(""#btnSaveFormAction"").attr(""disabled"", _userFormRole.IsInsert === false);

                    $(""#dvForm"").show();
                    $(""#jqgInternalForms"").GridUnload();
                    $('#txtFormID').prop('readonly', false);
                    $('#txtFormCode').prop('readonly', false);
                    $(""#dvNavigateURL"").show();
                    $('#txtFormID').val("""");
                    $('#txtFormCode').val("""");

                    $('#dvFormAction').hide();
                    $('#dvFormParameter').hide();
                   // eSyaParams.ClearValue();

                }
                // If Child node is selected
                else if (parentNode == ""FM"") {
                    $(""#pnlAddForms .mdl-card__title-text"").text(""");
            EndContext();
            BeginContext(17833, 21, false);
#line 398 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\Configure\Views\FormNames\ECA_01_00.cshtml"
                                                             Write(Localizer["EditForm"]);

#line default
#line hidden
            EndContext();
            BeginContext(17854, 75, true);
            WriteLiteral("\");\r\n\r\n                    $(\"#btnFMAdd\").html(\"<i class=\'fa fa-sync\'></i> ");
            EndContext();
            BeginContext(17930, 19, false);
#line 400 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\Configure\Views\FormNames\ECA_01_00.cshtml"
                                                               Write(Localizer["Update"]);

#line default
#line hidden
            EndContext();
            BeginContext(17949, 7643, true);
            WriteLiteral(@""");

                    $(""#btnFMAdd"").attr(""disabled"", _userFormRole.IsEdit === false);
                    $(""#btnSaveFormAction"").attr(""disabled"", _userFormRole.IsEdit === false);

                    $(""#dvForm"").show();

                    fnFillFormDetail(formID);

                    $('#dvFormAction').show();
                    fnTreeSize();
                }
                else {
                    $(""#dvForm"").hide();
                }

            }

        });

        $('#FormMasterTree').on(""close_node.jstree"", function (node) {
            var closingNode = node.handleObj.handler.arguments[1].node;
            $('#FormMasterTree').jstree().deselect_node(closingNode.children);
        });
    }

    //function fnIsStoreRequired(elem) {
    //    if (elem.checked) {
    //        $('#dvFormParameter').show();
    //    }
    //    else {
    //        $('#dvFormParameter').hide();
    //    }
    //}

    function fnFillFormDetail(formID) {

        $.aj");
            WriteLiteral(@"ax({
            url: getBaseURL() + '/FormNames/GetFormMasterByID',
            data: {
                formID: formID
            },
            success: function (result) {

                if (result != null) {

                    $('#txtFormID').prop('readonly', true);
                    $('#txtFormCode').prop('readonly', true);
                    $(""#dvNavigateURL"").hide();

                    $(""#txtFormID"").val(result.FormID);
                    $(""#txtFormCode"").val(result.FormCode);
                    $(""#txtFormDescription"").val(result.FormName);
                    $(""#txtControllerName"").val(result.ControllerName);
                    $(""#txtToolTip"").val(result.ToolTip);
                    $('#dvFormParameter').show();

                    //if (result.IsDocumentNumberRequired == true)
                    //    $('#chkIsDocumentNoRequired').parent().addClass(""is-checked"");
                    //else
                    //    $('#chkIsDocumentNoRequired').parent().re");
            WriteLiteral(@"moveClass(""is-checked"");

                    //if (result.IsStoreLink == true) {
                    //    $('#chkIsStoreLink').parent().addClass(""is-checked"");
                    //    $('#dvFormParameter').show();
                    //}
                    //else {
                    //    $('#chkIsStoreLink').parent().removeClass(""is-checked"");
                    //    $('#dvFormParameter').hide();
                    //}

                    //if (result.IsDoctor == true)
                    //    $('#chkIsDoctor').parent().addClass(""is-checked"");
                    //else
                    //    $('#chkIsDoctor').parent().removeClass(""is-checked"");

                   // eSyaParams.ClearValue();
                    //if (result.IsStoreLink == true) {
                    //    eSyaParams.SetJSONValue(result.l_FormParameter);
                    //}

                    fnLoadInternalFormGrid(formID)

                    $('#dvFormAction').show();
                    fnLoadF");
            WriteLiteral(@"ormActionGrid(formID);
                    fnLoadFormParameterGrid(formID);
                    $('#dvTable').hide();
                //    eSyaParams.SetJSONValue(result.l_FormParameter);
                }

            }
        });
    }

    function fnSaveFormMaster() {

        var txtFormID = $(""#txtFormID"").val();
        var formCode = $(""#txtFormCode"").val();
        var txtFormDescription = $(""#txtFormDescription"").val();

        var selectedNode = $('#FormMasterTree').jstree().get_selected(true)[0];

        var FormID = 0, parentID = 0;
        var isInsert = true;
        if (selectedNode != null) {
            if (selectedNode.parent != ""#"") {
                FormID = selectedNode.id;
                parentID = selectedNode.parent;
                isInsert = false;
            }
            else {
                FormID = txtFormID;
                parentID = 0;
            }
        }

        //if (IsStringNullorEmpty(txtFormID)) {
        //    //toastr.warni");
            WriteLiteral(@"ng(""Please enter the Form ID"");//""Please enter the Form ID"");
        //    toastr.warning(errorMsg[""E0011""]);
        //    return false;
        //}
        if (IsStringNullorEmpty(formCode)) {
            //toastr.warning(""Please enter the Form ID"");//""Please enter the Form ID"");
            toastr.warning(""Please enter the Form ID"");
            return false;
        }
        if (IsStringNullorEmpty(txtFormDescription)) {
            //toastr.warning(""Please enter the Form Description"");
            toastr.warning(errorMsg[""E0012""]);
            return false;
        }
        else if (isInsert && IsStringNullorEmpty($(""#txtControllerName"").val())) {
           // toastr.warning(""Please enter the Controller Name"");
            toastr.warning(errorMsg[""E0013""]);
            return false;
        }
        else {

          //  var fmParams = eSyaParams.GetJSONValue();

            $(""#btnFMAdd"").attr(""disabled"", true);
            $.ajax({
                url: getBaseURL() + '/For");
            WriteLiteral(@"mNames/InsertUpdateIntoFormMaster',
                type: 'POST',
                datatype: 'json',
                data: {
                    IsInsert: isInsert,
                    MenuItemID: 0,
                    FormID: FormID,
                    FormCode: formCode,
                    FormName: $(""#txtFormDescription"").val(),
                    ControllerName: $(""#txtControllerName"").val(),
                    ToolTip: $(""#txtToolTip"").val(),
                    //IsDocumentNumberRequired: $(""#chkIsDocumentNoRequired"").parent().hasClass(""is-checked""),
                    //IsStoreLink: $(""#chkIsStoreLink"").parent().hasClass(""is-checked""),
                    //IsDoctor: $(""#chkIsDoctor"").parent().hasClass(""is-checked""),

                    //l_FormParameter: fmParams
                },
                async: false,
                success: function (response) {

                    if (response.Status == true) {
                        toastr.success(""Form Updated"");
         ");
            WriteLiteral(@"               $(""#FormMasterTree"").jstree(""destroy"");
                        fnLoadFormsTree();

                        prevSelectedID = response.ID;
                        //prevSelectedID = FormID;
                        //fnFillFormDetail(FormID);

                    }
                    else {
                        toastr.error(response.Message);
                    }
                    $(""#btnFMAdd"").attr(""disabled"", false);
                },
                error: function (error) {
                    toastr.error(error.statusText);
                    $(""#btnFMAdd"").attr(""disabled"", false);
                }
            });
        }
    }

    function createNode(parent_node, new_node_id, new_node_text, position) {
        $('#FormMasterTree').jstree('create_node', $(parent_node), { ""text"": new_node_text, ""id"": new_node_id }, position, false, false);
    }

    function fnLoadInternalFormGrid(FormID) {

        $(""#jqgInternalForms"").GridUnload();

        $(""#");
            WriteLiteral(@"jqgInternalForms"").jqGrid({
            url: getBaseURL() + '/FormNames/GetInternalFormByFormID',
            datatype: ""json"",
            contenttype: ""application/json; charset-utf-8"",
            mtype: 'GET',
            postData: {
                formID: function () { return FormID; },
            },
            jsonReader: { repeatitems: false, root: ""rows"", page: ""page"", total: ""total"", records: ""records"" },
            colNames: [localization.FormID, """);
            EndContext();
            BeginContext(25593, 23, false);
#line 602 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\Configure\Views\FormNames\ECA_01_00.cshtml"
                                        Write(Localizer["InternalID"]);

#line default
#line hidden
            EndContext();
            BeginContext(25616, 4, true);
            WriteLiteral("\", \"");
            EndContext();
            BeginContext(25621, 16, false);
#line 602 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\Configure\Views\FormNames\ECA_01_00.cshtml"
                                                                    Write(Localizer["URL"]);

#line default
#line hidden
            EndContext();
            BeginContext(25637, 4, true);
            WriteLiteral("\", \"");
            EndContext();
            BeginContext(25642, 29, false);
#line 602 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\Configure\Views\FormNames\ECA_01_00.cshtml"
                                                                                         Write(Localizer["InternalFormDesc"]);

#line default
#line hidden
            EndContext();
            BeginContext(25671, 4, true);
            WriteLiteral("\", \"");
            EndContext();
            BeginContext(25676, 25, false);
#line 602 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\Configure\Views\FormNames\ECA_01_00.cshtml"
                                                                                                                           Write(Localizer["ActiveStatus"]);

#line default
#line hidden
            EndContext();
            BeginContext(25701, 6556, true);
            WriteLiteral(@"""],
            colModel: [
                { name: ""FormID"", width: 40, editable: false, editoptions: { disabled: true }, align: 'left', edittype: 'text', hidden: true },
                { name: ""InternalFormNumber"", width: 40, editable: true, align: 'left', edittype: 'text', hidden: false },
                { name: ""NavigateURL"", width: 140, editable: true, align: 'left', edittype: 'text', editoptions: { maxlength: 50 }, hidden: false },
                { name: ""FormDescription"", width: 70, editable: true, align: 'left', edittype: 'text', editoptions: { maxlength: 25 }, hidden: false },
                { name: ""ActiveStatus"", editable: true, width: 40, align: 'center !important', edittype: ""checkbox"", formatter: 'checkbox', editoptions: { value: ""true:false"" } },
            ],
            rowNum: 10,
            pager: ""#jqpInternalForms"",

            viewrecords: true,
            gridview: true,
            rownumbers: true,
            height: 'auto',
            width: 'auto',
        ");
            WriteLiteral(@"    autowidth: true,
            shrinkToFit: true,
            forceFit: true,
            loadonce: true,

            editurl: getBaseURL() + '/FormNames/InsertIntoInternalForm',
            beforeSubmit: function (postdata, formid) {
                return [success, message];
            },
            ondblClickRow: function (rowid) {
            },
            loadComplete: function (data) {
                $(this).find("">tbody>tr.jqgrow:odd"").addClass(""myAltRowClassEven"");
                $(this).find("">tbody>tr.jqgrow:even"").addClass(""myAltRowClassOdd"");
                $(""#jqgInternalForms"").setGridParam({ datatype: 'json', page: 1 }).trigger('reloadGrid');

                SetGridControlByAction(""jqgInternalForms"");
            },
        }).jqGrid('navGrid', '#jqpInternalForms', { add: false, edit: false, search: false, del: false, refresh: false });

        $(""#jqgInternalForms"").jqGrid('inlineNav', '#jqpInternalForms',
            {
                edit: true,
            ");
            WriteLiteral(@"    editicon: "" fa fa-pen"",
                edittext: "" Edit"",
                add: true,
                addicon: ""fa fa-plus"",
                addtext: "" Add"",
                save: true,
                savetext: "" Save"",
                saveicon: ""fa fa-save"",
                cancelicon: ""fa fa-ban"",
                canceltext: "" Cancel"",
                editParams: {
                    keys: false,
                    oneditfunc: function (result) {
                        var id = $(""#jqgInternalForms"").jqGrid('getGridParam', 'selrow');
                        $('#' + id + '_InternalFormNumber').prop('disabled', true);
                        $('#' + id + '_NavigateURL').prop('disabled', true);
                    },
                    url: null,
                    extraparam: {
                        FormID: function () { return FormID; },
                    },
                    successfunc: function (result) {
                        if (result.responseJSON.Status === true");
            WriteLiteral(@") {
                            toastr.success(result.responseJSON.Message);
                            $(""#FormMasterTree"").jstree(""destroy"");
                            fnLoadFormsTree();
                            $(""#jqgInternalForms"").setGridParam({ datatype: 'json', page: 1 }).trigger('reloadGrid');

                        }
                        else {
                            toastr.error(result.responseJSON.Message);
                        }
                    },
                    aftersavefun:null,
                    errorfun: null,
                    afterrestorefun:null,
                    restoreAfterError: false,
                    mtype: ""POST"",
                },

                addParams: {
                    useDefValues: true,
                    position: ""last"",
                    addRowParams: {
                        keys: true,
                        oneditfunc: function (rowID) {
                            $('#' + rowID + '_InternalFormNu");
            WriteLiteral(@"mber').prop('disabled', true);
                            $('#' + rowID + '_NavigateURL').prop('disabled', true);

                            $.ajax({
                                url: getBaseURL() + '/FormNames/GetNextInternalFormByID',
                                data: {
                                    formID: FormID
                                },
                                success: function (result) {
                                    $('#' + rowID + '_InternalFormNumber').val(result.InternalFormNumber);
                                    $('#' + rowID + '_NavigateURL').val(result.NavigateURL);
                                }
                            });
                        },
                        extraparam: {
                            FormID: function () { return FormID; },
                        },
                        successfunc: function (result) {
                            if (result.responseJSON.Status === true) {
                     ");
            WriteLiteral(@"           toastr.success(result.responseJSON.Message);
                                $(""#FormMasterTree"").jstree(""destroy"");
                                fnLoadFormsTree();
                                $(""#jqgInternalForms"").setGridParam({ datatype: 'json', page: 1 }).trigger('reloadGrid');

                                return true;
                            }
                            else {
                                toastr.error(result.responseJSON.Message);
                                return false;
                            }
                        },
                        aftersavefun: null,
                        errorfun: null,
                        afterrestorefun: null,
                        restoreAfterError: false,
                        mtype: ""POST"",
                    }
                },
            });


        //$('#jqgInternalForms_iladd').addClass('ui-state-disabled');

    }


    function fnLoadFormActionGrid(FormID) {

  ");
            WriteLiteral(@"      $(""#jqgFormAction"").GridUnload();
        $('#btnSaveFormAction').show();

        $(""#jqgFormAction"").jqGrid({
            url: getBaseURL() + '/FormNames/GetFormActionByID',
            datatype: ""json"",
            mtype: 'POST',
            rownumbers: true,
            postData: {
                formID: function () { return FormID; },
            },
            colNames: [""Action ID"", """);
            EndContext();
            BeginContext(32258, 19, false);
#line 746 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\Configure\Views\FormNames\ECA_01_00.cshtml"
                                Write(Localizer["Action"]);

#line default
#line hidden
            EndContext();
            BeginContext(32277, 4, true);
            WriteLiteral("\", \"");
            EndContext();
            BeginContext(32282, 25, false);
#line 746 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\Configure\Views\FormNames\ECA_01_00.cshtml"
                                                        Write(Localizer["ActiveStatus"]);

#line default
#line hidden
            EndContext();
            BeginContext(32307, 3134, true);
            WriteLiteral(@"""],
            colModel: [
                { name: 'ActionId', key: true, index: 'ActionId', width: 0, sortable: false, hidden: true },
                { name: 'ActionDesc', index: 'ActionDesc', width: 150, sortable: false },
                { name: 'ActiveStatus', index: 'ActiveStatus', width: 75, align: 'center', sortable: false, formatter: 'checkbox', editable: true, edittype: ""checkbox"" }
            ],
            caption: """",
            height: '100',
            width: '200',
            rowNum:100,
            viewrecords: true,
            gridview: true,
            loadonce:true,
            autowidth: true,
            shrinkToFit: true,
            forceFit: true,
            cellEdit: true,
            onSelectRow: function (id) {
                if (id) { $('#jqgFormAction').jqGrid('editRow', id, true); }
            },
            loadComplete: function () {
                var ids = $('#jqgFormAction').jqGrid('getDataIDs');
                var i = 0;
                f");
            WriteLiteral(@"or (i = 0; i < ids.length; i++) {
                    if (ids[i])
                        $('#jqgFormAction').jqGrid('editRow', ids[i]);
                }
            }
        });
        //debugger;
        fnTreeSize();

    }

    function fnSaveFormAction() {
        var $grid = $(""#jqgFormAction"")
        var l_formAction = [];
        var ids = jQuery(""#jqgFormAction"").jqGrid('getDataIDs');
        for (var i = 0; i < ids.length; i++) {
            var rowId = ids[i];
            var rowData = jQuery('#jqgFormAction').jqGrid('getRowData', rowId);
            if (rowData.ActiveStatus == ""Yes"") {
                l_formAction.push({ ActionId: rowData.ActionId })
            }
        }

        $(""#btnSaveFormAction"").attr(""disabled"", true);
        $.ajax({
            url: getBaseURL() + '/FormNames/InsertIntoFormAction',
            type: 'POST',
            datatype: 'json',
            data: {
                FormID: $(""#txtFormID"").val(),
                l_FormAction: l");
            WriteLiteral(@"_formAction
            },
            async: false,
            success: function (response) {
                if (response.Status == true) {
                    toastr.success(""Form Action Updated"");
                }
                else {
                    toastr.error(response.Message);
                }
                $(""#btnSaveFormAction"").attr(""disabled"", false);
            },
            error: function (error) {
                toastr.error(error.statusText);
                $(""#btnSaveFormAction"").attr(""disabled"", false);
            }
        });

    }

    function fnLoadFormParameterGrid(FormID)
    {

        $(""#jqgFormParameter"").GridUnload();
         $('#btnSaveFormParameter').show();

         $(""#jqgFormParameter"").jqGrid({
             url: getBaseURL() + '/FormNames/GetFormParameterByID',
            datatype: ""json"",
            mtype: 'POST',
            rownumbers: true,
            postData: {
                formID: function () { return FormID;");
            WriteLiteral(" },\r\n            },\r\n             colNames: [\"Parameter ID\", \"");
            EndContext();
            BeginContext(35442, 22, false);
#line 833 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\Configure\Views\FormNames\ECA_01_00.cshtml"
                                    Write(Localizer["Parameter"]);

#line default
#line hidden
            EndContext();
            BeginContext(35464, 4, true);
            WriteLiteral("\", \"");
            EndContext();
            BeginContext(35469, 25, false);
#line 833 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\Configure\Views\FormNames\ECA_01_00.cshtml"
                                                               Write(Localizer["ActiveStatus"]);

#line default
#line hidden
            EndContext();
            BeginContext(35494, 4556, true);
            WriteLiteral(@"""],
            colModel: [
                { name: 'ParameterId', key: true, index: 'ParameterId', width: 0,  sortable: false, hidden: true },
                { name: 'ParameterDesc', index: 'ParameterDesc',  classes: 'ellip', width: 150, sortable: false },
                {
                    name: 'ActiveStatus', index: 'ActiveStatus', width: 75, align: 'center', sortable: false, formatter: 'checkbox', editable: true, edittype: ""checkbox"",
                    cellattr: function (id, val, rawdata, cm, rdata) {
                        ret = """"
                        if (rdata['ParameterId'] == 1) {
                            console.log(rdata['ParameterId']);
                            ret = "" class='not-editable-cell'"";
                        }
                        return ret;
                    }}
            ],
            caption: """",
            height: '100',
            width: '200',
            rowNum:100,
            viewrecords: true,
            gridview: true,
      ");
            WriteLiteral(@"      loadonce:true,
            autowidth: true,
            shrinkToFit: true,
            forceFit: true,
             cellEdit: false,
             onCellSelect: function (rowId, iCol, content, event) {
                 var rowData = $('#jqgFormParameter').jqGrid('getRowData', rowId);
                 if (rowData.ParameterId == 1) {
                     $(""#jqgFormParameter"").setColProp('ActiveStatus', { editable: false });
                 }
             },
             onSelectRow: function (id) {

                 $('#dvTable').show();
                 parameterId = $(""#jqgFormParameter"").jqGrid('getCell', id, 'ParameterId');
                 _parameterId = parameterId;
                 console.log(""param : ""+_parameterId);
                 fnLoadFormSubParameterGrid(FormID, parameterId);

             },
             ondblClickRow: function (rowid) {
              //   alert(1);
             },
            loadComplete: function () {
                var ids = $('#jqgFormParamet");
            WriteLiteral(@"er').jqGrid('getDataIDs');
                var i = 0;
                for (i = 0; i < ids.length; i++) {
                    if (ids[i] && i > 0)
                        $('#jqgFormParameter').jqGrid('editRow', ids[i]);
                }
                $('#dvTable').hide();
            }
        });
     //   debugger;
        fnTreeSize();

    }

    var _parameterId = 0;
    function fnSaveFormParameter() {
        var $grid = $(""#jqgFormParameter"")
        var l_formParameter = [];
        var ids = jQuery(""#jqgFormParameter"").jqGrid('getDataIDs');
        for (var i = 0; i < ids.length; i++) {
            var rowId = ids[i];
            var rowData = jQuery('#jqgFormParameter').jqGrid('getRowData', rowId);
            if (rowData.ActiveStatus == ""Yes"") {
                l_formParameter.push({ ParameterId: rowData.ParameterId, ActiveStatus: true })
            }
        }

        $(""#btnSaveFormParameter"").attr(""disabled"", true);
        $.ajax({
            url: getBaseURL(");
            WriteLiteral(@") + '/FormNames/InsertIntoFormParameter',
            type: 'POST',
            datatype: 'json',
            data: {
                FormID: $(""#txtFormID"").val(),
                l_FormParameter: l_formParameter
            },
            async: false,
            success: function (response) {
                if (response.Status == true) {
                    toastr.success(""Form Parameter Updated"");
                    fnLoadFormParameterGrid($(""#txtFormID"").val());
                }
                else {
                    toastr.error(response.Message);
                }
                $(""#btnSaveFormParameter"").attr(""disabled"", false);
            },
            error: function (error) {
                toastr.error(error.statusText);
                $(""#btnSaveFormParameter"").attr(""disabled"", false);
            }
        });

    }

     function fnLoadFormSubParameterGrid(FormID, parameterId) {

         $(""#jqgFormSubParameter"").GridUnload();
         $('#btnSaveForm");
            WriteLiteral(@"SubParameter').show();
        // debugger;
         $(""#jqgFormSubParameter"").jqGrid({
             url: getBaseURL() + '/FormNames/GetFormSubParameterByID',
            datatype: ""json"",
            mtype: 'POST',
            rownumbers: true,
            postData: {
                formID: function () { return FormID; },
                parameterId: function () { return parameterId; },
            },
             colNames: [ ""Parameter ID"", """);
            EndContext();
            BeginContext(40051, 26, false);
#line 947 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\Configure\Views\FormNames\ECA_01_00.cshtml"
                                     Write(Localizer["Sub Parameter"]);

#line default
#line hidden
            EndContext();
            BeginContext(40077, 4, true);
            WriteLiteral("\", \"");
            EndContext();
            BeginContext(40082, 25, false);
#line 947 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\Configure\Views\FormNames\ECA_01_00.cshtml"
                                                                    Write(Localizer["ActiveStatus"]);

#line default
#line hidden
            EndContext();
            BeginContext(40107, 8522, true);
            WriteLiteral(@"""],
             colModel: [

                { name: 'SubParameterId', key: true, index: 'SubParameterId', width: 0, sortable: false, hidden: true },
                { name: 'SubParameterDesc', index: 'SubParameterDesc', width: 300, sortable: false },
                 { name: 'ActiveStatus', index: 'ActiveStatus', width: 75, align: 'center', sortable: false, formatter: 'checkbox', editable: true, edittype: ""checkbox"" }
            ],
            caption: """",
            height: '95',
            width: '400',
            rowNum:100,
            viewrecords: true,
            gridview: true,
            loadonce:true,
            autowidth: true,
            shrinkToFit: true,
            forceFit: true,
            cellEdit: true,
             onSelectRow: function (id) {
                if (id) { $('#jqgFormSubParameter').jqGrid('editRow', id, true); }
            },
            loadComplete: function () {
                var ids = $('#jqgFormSubParameter').jqGrid('getDataIDs');
     ");
            WriteLiteral(@"           var i = 0;
                for (i = 0; i < ids.length; i++) {
                    if (ids[i])
                        $('#jqgFormSubParameter').jqGrid('editRow', ids[i]);
                }

            }
         });


         fnTreeSize();


    }

    function fnSaveFormSubParameter() {
        var $grid = $(""#jqgFormSubParameter"")
        var l_formSubParameter = [];
        var ids = jQuery(""#jqgFormSubParameter"").jqGrid('getDataIDs');
        for (var i = 0; i < ids.length; i++) {
            var rowId = ids[i];
            var rowData = jQuery('#jqgFormSubParameter').jqGrid('getRowData', rowId);
            if (rowData.ActiveStatus == ""Yes"") {
                l_formSubParameter.push({ SubParameterId: rowData.SubParameterId })
            }
        }

        $(""#btnSaveFormSubParameter"").attr(""disabled"", true);
        $.ajax({
            url: getBaseURL() + '/FormNames/InsertIntoFormSubParameter',
            type: 'POST',
            datatype: 'json',
     ");
            WriteLiteral(@"       data: {
                FormID: $(""#txtFormID"").val(),
                ParameterId: _parameterId,
                l_FormSubParameter: l_formSubParameter
            },
            async: false,
            success: function (response) {
                if (response.Status == true) {
                    toastr.success(""Form Sub Parameter Updated"");
                   // $('#PopupSubParameter').modal('hide');
                    fnLoadFormParameterGrid($(""#txtFormID"").val());
                    $('#dvTable').hide();
                }
                else {
                    toastr.error(response.Message);
                }
                $(""#btnSaveFormSubParameter"").attr(""disabled"", false);
            },
            error: function (error) {
                toastr.error(error.statusText);
                $(""#btnSaveFormSubParameter"").attr(""disabled"", false);
            }
        });

    }

    function fnShowUserAction_onclick() {

        fnLoadUserAction();
        ");
            WriteLiteral(@"$(""#popupUserAction"").modal('show');
    }

    function fnLoad_UserAction() {

        UserActionList = [];
        _userActionlist = [];
        var ht = 280;
        $('#lbxUserAction').html('');
        $('#lbxUserAction').append('<div class=""col-sm-12 col-lg-12 col-md-12""><select id=""source_4"" data-search=""Search""></select></div><div class=""col-sm-6 col-lg-6 col-md-6 col-xs-6""><select id=""destination_4"" data-search=""Search""></select></div>')

        $('#lbxUserAction #source_4,#lbxUserAction #destination_4').listswap({
            truncate: true,
            height: ht,
            is_scroll: true,
        });

        var list_UserAction = [];
        $.ajax({
            'async': false,
            url: getBaseURL() + ""/ConfigureMenu/Get_ActionList"",
            type: 'get',
            dataType: 'json',
            success: function (json) {
                list_UserAction = json;
            }
        });
        var l_Existing_UserAction = [];
        $.ajax({
         ");
            WriteLiteral(@"   'async': false,
            url: getBaseURL() + ""/ConfigureMenu/Get_FormMenuLink?FormID="" + $(txtFID).val(),
            type: 'get',
            dataType: 'json',
            contentType: 'application/Json; charSet=utf-8',

            success: function (json) {
                l_Existing_UserAction = json;
            }
        });

        l_Existing_UserAction = $.grep(l_Existing_UserAction, function (data, i) {
            return (l_Existing_UserAction.findIndex(x => x.ActionId == data.ActionId) != -1)
        });

        list_UserAction = $.grep(list_UserAction, function (data, i) {
            return (list_UserAction.findIndex(x => x.ActionId == data.ActionId) != -1)
        });

        $('#lbxUserAction #source_4,#lbxUserAction #destination_4').empty();
        $('#lbxUserAction #listboxswap_1 div#listbox_destination_4_wrapper ul').html("""");
        $('#lbxUserAction #listboxswap_1 div#listbox_source_4_wrapper ul').html("""");
        $('[name=""search_listbox""]').val('');
   ");
            WriteLiteral(@"     //Assign Values to Left Side Panel
        $.each(list_UserAction, function (i, obj) {
            if ((l_Existing_UserAction.findIndex(x => x.ActionId == obj.ActionId) == -1)) {
                $('#lbxUserAction #source_4').append($('<option>').text(obj.ActionDesc).attr('value', obj.ActionId));
                var element = '<li class=""listbox_option"" data-value=""' + obj.ActionId + '"" data-actiondesc=""' + obj.ActionDesc + '"">' + obj.ActionDesc + '</span></li>';
                $('#lbxUserAction #listboxswap_1 div#listbox_source_4_wrapper ul').append(element);
            }
        });

        $('#lbxUserAction #listboxswap_1 .source_wrapper .listbox_option').click(function () {
            if ($(this).parent().parent().get(0).className === ""source_wrapper"") {
                add_remove_handler($(this), div_id + ' .destination_wrapper ul', source_select_id, destination_select_id);
            }
            else {
                $(this).toggleClass('selected');
            }
        });");
            WriteLiteral(@"

        // Add Existing States in Destination Box


        $.each(l_Existing_UserAction, function (i, obj) {
            $('#lbxUserAction #destination_4').append($('<option>').text(obj.ActionDesc).attr('value', obj.ActionId));
            var element = '<li class=""listbox_option"" data-value=""' + obj.ActionId + '"" data-statedesc=""' + obj.ActionDesc + '"">' + obj.ActionDesc + '</span></li>';
            $('#lbxUserAction #listboxswap_1 div#listbox_destination_4_wrapper ul').append(element);
        });

        $('#lbxUserAction #listboxswap_1 .destination_wrapper .listbox_option').click(function () {
            $(this).toggleClass('selected');
        });
    }

    function fnAddUserAction_onclick() {

        UserActionList = [];
        _userActionlist = [];
        $(""#lbxUserAction #destination_4 option"").each(function () {
            var ActionId = Number($(this).val());
            var FormId = Number($(txtFID).val());
            _userActionlist.push({ ActionId: ActionId, For");
            WriteLiteral(@"mId: FormId });
        });

        var _FormId = Number($(txtFID).val());
        if (_userActionlist.length <= 0) {

            alert(""Please select any Action"");
        }
        else {

            $.ajax({
                contentType: 'application/Json; charSet=utf-8',
                datatype: 'JSON',
                type: 'POST',
                url: getBaseURL() + '/ConfigureMenu/InsertOrUpdate_FormMenuLink',
                data: _userActionlist,
                data: JSON.stringify(_userActionlist),
                success: function (response, postdata) {
                    UserActionList = [];
                    $(""#fa"").hide();
                    var par = JSON.parse(response);
                    if (par.Status == true) {

                        toastr.success(par.Message);
                        $(""#popupUserAction"").modal('hide');
                        return [true, '']
                    }
                    else {
                        toastr.error(re");
            WriteLiteral(@"sponse.Message);
                        return [false, response.Message]
                    }
                }
            });

        }
    }


    $(""#popupUserAction"").on('hidden.bs.modal', function () {
        $('#lbxUserAction').html('');
    });

    function fnOpenConfigureMenu() {
         var url = '");
            EndContext();
            BeginContext(48630, 59, false);
#line 1165 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\Configure\Views\FormNames\ECA_01_00.cshtml"
               Write(Url.Action("ECA_02_00", "Menu", new { area = "Configure" }));

#line default
#line hidden
            EndContext();
            BeginContext(48689, 503, true);
            WriteLiteral(@"';
         window.location.href = url;
    }

   function  SetGridControlByAction(jqg)
    {
        $('#' +jqg+'_iladd').removeClass('ui-state-disabled');
        $('#' + jqg +'_iledit').removeClass('ui-state-disabled');
        if (_userFormRole.IsInsert === false) {
            $('#' + jqg +'_iladd').addClass('ui-state-disabled');
        }
        if (_userFormRole.IsEdit === false)
            $('#' + jqg +'_iledit').addClass('ui-state-disabled');
    }

</script>






");
            EndContext();
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public IViewLocalizer Localizer { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<dynamic> Html { get; private set; }
    }
}
#pragma warning restore 1591
