#pragma checksum "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\eSyaOutPatient\Views\PatientClinicalForms\PatientForm.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "2c0d775fbc51e50e3db64b96e543bdd0715d95c6"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.Areas_eSyaOutPatient_Views_PatientClinicalForms_PatientForm), @"mvc.1.0.view", @"/Areas/eSyaOutPatient/Views/PatientClinicalForms/PatientForm.cshtml")]
[assembly:global::Microsoft.AspNetCore.Mvc.Razor.Compilation.RazorViewAttribute(@"/Areas/eSyaOutPatient/Views/PatientClinicalForms/PatientForm.cshtml", typeof(AspNetCore.Areas_eSyaOutPatient_Views_PatientClinicalForms_PatientForm))]
namespace AspNetCore
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
#line 1 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\eSyaOutPatient\Views\PatientClinicalForms\PatientForm.cshtml"
using Microsoft.AspNetCore.Mvc.Localization;

#line default
#line hidden
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"2c0d775fbc51e50e3db64b96e543bdd0715d95c6", @"/Areas/eSyaOutPatient/Views/PatientClinicalForms/PatientForm.cshtml")]
    public class Areas_eSyaOutPatient_Views_PatientClinicalForms_PatientForm : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<dynamic>
    {
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_0 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("href", new global::Microsoft.AspNetCore.Html.HtmlString("~/css/material.min.css"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_1 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("rel", new global::Microsoft.AspNetCore.Html.HtmlString("stylesheet"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_2 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("href", new global::Microsoft.AspNetCore.Html.HtmlString("~/css/eSyaNursingStation/patientClinicalInformation.css"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_3 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("src", new global::Microsoft.AspNetCore.Html.HtmlString("~/js/eSyaOutPatient/PatientClinicalForms/patientform.js"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_4 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("src", new global::Microsoft.AspNetCore.Html.HtmlString("~/js/material.min.js"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        #line hidden
        #pragma warning disable 0169
        private string __tagHelperStringValueBuffer;
        #pragma warning restore 0169
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext __tagHelperExecutionContext;
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner __tagHelperRunner = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner();
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __backed__tagHelperScopeManager = null;
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __tagHelperScopeManager
        {
            get
            {
                if (__backed__tagHelperScopeManager == null)
                {
                    __backed__tagHelperScopeManager = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager(StartTagHelperWritingScope, EndTagHelperWritingScope);
                }
                return __backed__tagHelperScopeManager;
            }
        }
        private global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper;
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
#line 3 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\eSyaOutPatient\Views\PatientClinicalForms\PatientForm.cshtml"
  
    ViewData["Title"] = "Patient Form";
    if (ViewBag.IsApp == "Y")
    {
        Layout = "~/Views/Shared/_Layout_m.cshtml";
    }
    else
    {
        Layout = "~/Views/Shared/_Layout.cshtml";
    }

#line default
#line hidden
            BeginContext(301, 2, true);
            WriteLiteral("\r\n");
            EndContext();
            BeginContext(303, 55, false);
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("link", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.SelfClosing, "2c0d775fbc51e50e3db64b96e543bdd0715d95c65525", async() => {
            }
            );
            __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_0);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_1);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            EndContext();
            BeginContext(358, 2, true);
            WriteLiteral("\r\n");
            EndContext();
            BeginContext(360, 88, false);
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("link", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.SelfClosing, "2c0d775fbc51e50e3db64b96e543bdd0715d95c66777", async() => {
            }
            );
            __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_2);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_1);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            EndContext();
            BeginContext(448, 2, true);
            WriteLiteral("\r\n");
            EndContext();
            DefineSection("scripts", async() => {
                BeginContext(467, 8, true);
                WriteLiteral("\r\n\r\n    ");
                EndContext();
                BeginContext(475, 79, false);
                __tagHelperExecutionContext = __tagHelperScopeManager.Begin("script", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "2c0d775fbc51e50e3db64b96e543bdd0715d95c68211", async() => {
                }
                );
                __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper>();
                __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_3);
                await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
                if (!__tagHelperExecutionContext.Output.IsContentModified)
                {
                    await __tagHelperExecutionContext.SetOutputContentAsync();
                }
                Write(__tagHelperExecutionContext.Output);
                __tagHelperExecutionContext = __tagHelperScopeManager.End();
                EndContext();
                BeginContext(554, 6, true);
                WriteLiteral("\r\n    ");
                EndContext();
                BeginContext(560, 44, false);
                __tagHelperExecutionContext = __tagHelperScopeManager.Begin("script", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "2c0d775fbc51e50e3db64b96e543bdd0715d95c69464", async() => {
                }
                );
                __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper>();
                __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_4);
                await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
                if (!__tagHelperExecutionContext.Output.IsContentModified)
                {
                    await __tagHelperExecutionContext.SetOutputContentAsync();
                }
                Write(__tagHelperExecutionContext.Output);
                __tagHelperExecutionContext = __tagHelperScopeManager.End();
                EndContext();
                BeginContext(604, 4, true);
                WriteLiteral("\r\n\r\n");
                EndContext();
            }
            );
            BeginContext(611, 772, true);
            WriteLiteral(@"


<style>
    .lblCheck {
        display: flex;
        align-items: center;
    }

    label span {
        padding-left: 5px;
    }
    /*.ui-jqgrid .ui-jqgrid-bdiv {
        overflow-x: auto;
    }*/

    .ui-jqgrid .ui-jqgrid-bdiv {
        /*position: relative;
        margin: 0;
        padding: 0;*/
        overflow: auto;
        text-align: left;
    }

    .ui-state-default ui-th-column-header ui-th-ltr {
        background: #555 !important;
        color: bisque !important;
    }

    .ui-jqgrid .ui-jqgrid-htable th {
        background: #555 !important;
        color: gold !important;
    }

    .jqg-first-row-header {
        visibility: collapse !important;
    }
</style>


<input type=""hidden"" id=""hdfType""");
            EndContext();
            BeginWriteAttribute("value", " value=\"", 1383, "\"", 1405, 1);
#line 63 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\eSyaOutPatient\Views\PatientClinicalForms\PatientForm.cshtml"
WriteAttributeValue("", 1391, ViewBag.fType, 1391, 14, false);

#line default
#line hidden
            EndWriteAttribute();
            BeginContext(1406, 37, true);
            WriteLiteral(" />\r\n<input type=\"hidden\" id=\"hdUHID\"");
            EndContext();
            BeginWriteAttribute("value", " value=\"", 1443, "\"", 1464, 1);
#line 64 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\eSyaOutPatient\Views\PatientClinicalForms\PatientForm.cshtml"
WriteAttributeValue("", 1451, ViewBag.UHID, 1451, 13, false);

#line default
#line hidden
            EndWriteAttribute();
            BeginContext(1465, 4688, true);
            WriteLiteral(@" />

<div class=""divFixedBar"">
    <div class=""row mr-0"">
        <div class=""col-xl-4 col-lg-6 col-md-6 col-sm-12 col-xs-12 d-flex align-items-center"">

            <div>
                <p><span class=""labelname""><i class=""fas fa-chevron-right c-lightgrey""></i> MRN:</span> <span id=""lblPatientID""></span>&nbsp;<span class=""labelname""> Patient Name:</span><span id=""lblPatientName""></span></p>
                <p><span class=""labelname""><i class=""fas fa-chevron-right c-lightgrey""></i> Surgery:</span><span id=""lblSurgery""></span>&nbsp;<span class=""labelname""> Date:</span><span id=""lblSurgeryDate""></span></p>
            </div>
        </div>
        <div class=""col-xl-4 col-lg-6 col-md-6 col-sm-12 col-xs-12 d-flex align-items-center"">

            <div>
                <p><span class=""labelname""><i class=""fas fa-chevron-right c-lightgrey""></i> Email:</span><span id=""lblEmail""></span>&nbsp;<span class=""labelname""> Tel:</span><span id=""lblTel""></span></p>
                <p><span class=""labelname""><");
            WriteLiteral(@"i class=""fas fa-chevron-right c-lightgrey""></i> Weight:</span><span id=""lblBMI""></span></p>

            </div>
        </div>
        <div class=""col-xl-2 col-lg-6 col-md-6 col-sm-12 col-xs-12 d-flex align-items-center"">

            <div>
                <p><span class=""labelname""><i class=""fas fa-chevron-right c-lightgrey""></i> Gender:</span><span id=""lblGender""></span>&nbsp;&nbsp;<span class=""labelname""> Age:</span><span id=""lblAge""></span></p>
                <p>&nbsp;&nbsp;</p>
            </div>
        </div>
        <div id=""floatButtons"" class=""col-xl-2 col-lg-12 text-right p-0"" >
            <button class=""mdl-button"" id=""btnBackNS"" onclick=""fnBack()"" ><i class=""fas fa-chevron-left""></i> <span class=""btntext"">Back</span></button>
                 </div>
    </div>
</div>

<div class=""row"" style=""margin-right: 0px !important;"">
    <div class=""col-lg-3 col-md-3 col-sm-3 sidebar"" id=""navbar-preoperative"">
        <div class=""sidebar-sticky"">
            <ul class=""nav flex-column""");
            WriteLiteral(@" id=""nav_menu"">
                <li><a href=""#"" id=""v-f1-tab"" data-bs-toggle=""pill"" data-bs-target=""#v-f1"" class=""nav-link active"" role=""tab"" aria-controls=""v-f1"" aria-selected=""true"">Forms</a></li>
                <li><a href=""#"" onclick=""fnAddForm()"" id=""v-f1-tab"" data-bs-toggle=""pill"" data-bs-target=""#v-f1"" class=""nav-link"" role=""tab"" aria-controls=""v-f1"" >Add Form</a></li>
            </ul>
        </div>
    </div>
    <div class="""" id=""mainContent"">
        <div class=""tab-content"" id=""v-pills-tabContent"">

            <div class=""tab-pane fade show active"" id=""v-f1"" role=""tabpanel"" aria-labelledby=""v-f1-tab"">
                <div class=""row"">
                    <div class=""col-12 p-0"">
                        <h6 class=""main-heading""><i class=""fa fa-bars mr-10""></i>Forms</h6>
                    </div>
                </div>
                <div class=""row mr-0"" style=""margin-right:0px;"">
                    <div class=""col-lg-12 col-md-12 col-sm-12 mb-2 divNursingCarePlan"">
         ");
            WriteLiteral(@"               
                            <table id=""jqgFormDetail""></table>
                            <div id=""jqpFormDetail""></div>
                       
                    </div>
                </div>
            </div>


        </div>
    </div>
</div>


<script>

    $("".nav li a"").click(function () {
        $("".nav li a"").removeClass(""active"");
        $(this).addClass(""active"");
        $('.tab-pane').removeClass('show active');
        var v = $(this).attr('data-bs-target');
        //console.log(v);
        $(v).addClass('show active');
    });

    $(document).ready(function () {

    });

    function fnBackToNSGrid() {
        //   window.location.href = getBaseURL() + ""/eSyaNursingStation/OperativeAnaesthesiaCare/V_6004_00"";
    }
    function fnBack() {
       
                    history.back();

    }
      function fnsideBarSetup() {
      var docWidth = $(document).width();
    var marginLeft = $(""#navbar-preoperative"").outerWidth(true);
    ");
            WriteLiteral(@"var winH = $(window).outerHeight(true);
    var divHeight = Math.floor($("".divFixedBar"").outerHeight(true)) - 1;
    var maxH = ($(window).outerHeight(true) - ($(""section.header"").outerHeight(true) + $("".banner"").outerHeight(true) + $("".divFixedBar"").outerHeight(true)))
    const headerH = $('section.header').outerHeight(true);
    const headerBannerH = headerH + $('.banner').outerHeight(true);
    const headerBannerFixedBarH = headerBannerH + $('.divFixedBar').outerHeight(true);
    const tabContentH = headerBannerFixedBarH + $('.main-heading').height();
    
    var isapp = '");
            EndContext();
            BeginContext(6154, 13, false);
#line 164 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\eSyaOutPatient\Views\PatientClinicalForms\PatientForm.cshtml"
            Write(ViewBag.IsApp);

#line default
#line hidden
            EndContext();
            BeginContext(6167, 2625, true);
            WriteLiteral(@"';
     
    if (isapp == ""Y"") {
        $(""#mainContent"").css({
            ""top"": $('.divFixedBar').innerHeight(),
            'max-height': winH - $('.divFixedBar').outerHeight(true),
            'margin-left': marginLeft,
            'overflow-y': 'auto',
            'width': '100%'
        });
        $("".sidebar"").css({
            'top': $('.divFixedBar').innerHeight(),
            'display': 'block',
            'overflow-y': 'auto',
            'max-height': maxH
        });
        $(""#floatButtons"").css({
            'position': 'absolute',
            'top': $('.divFixedBar').height(),
            'right': '0px',
            'z-index': 3
        });
        $(""#floatButtons button"").css({
            'height': $('.main-heading').innerHeight()
        });
        $(""#floatButtons button svg"").css({
            ""font-size"": $(""#floatButtons button"").height() / 2
        });
    }
    else {
        $(""#mainContent"").css({
            ""top"": $(""section.header"").outerHei");
            WriteLiteral(@"ght(true) + $("".banner"").outerHeight(true) + $("".divFixedBar"").outerHeight(true),
            'max-height': winH - $('.divFixedBar').outerHeight(true),
            'margin-left': marginLeft,
            'overflow-y': 'auto',
            'width': '100%'
        });
        $("".sidebar"").css({
            'top': $(""section.header"").outerHeight(true) + $("".banner"").outerHeight(true) + $("".divFixedBar"").outerHeight(true),
            'display': 'block',
            'overflow-y': 'auto',
            'max-height': maxH
        });
        $(""#floatButtons button"").css({
            'height': $("".divFixedBar"").outerHeight(true)
        });
        $(""#floatButtons button svg"").css({
            ""font-size"": $("".divFixedBar"").outerHeight(true) / 2
        });
    }



    $(""#navbar-preoperative"").on('click', 'a', function () {
        $("".nav-link"").removeClass(""active"");
        $(this).addClass(""active"");
        $('.tab-pane').removeClass('show active');
        var v = $(this).attr('dat");
            WriteLiteral(@"a-bs-target');
        $(v).addClass('show active');

        var _wW = $(window).width();
        if (_wW < 1024) {
            $('.sidebar').addClass('hide');
            $('#mainContent').toggleClass('moveLeft').css('width', '100% ');
        }
        else {
            $('#mainContent').css('width', '100%');
        }

        $(""#mainContent"").scrollTop(0);
    });
    fnRefreshGridWidth();
        }
        $(window).resize(function () {
            fnsideBarSetup()
        })

</script>
<script>
 var localization = {
        PreOperative: '");
            EndContext();
            BeginContext(8793, 25, false);
#line 244 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\eSyaOutPatient\Views\PatientClinicalForms\PatientForm.cshtml"
                  Write(Localizer["PreOperative"]);

#line default
#line hidden
            EndContext();
            BeginContext(8818, 27, true);
            WriteLiteral("\',\r\n        FacilityStay: \'");
            EndContext();
            BeginContext(8846, 25, false);
#line 245 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\eSyaOutPatient\Views\PatientClinicalForms\PatientForm.cshtml"
                  Write(Localizer["FacilityStay"]);

#line default
#line hidden
            EndContext();
            BeginContext(8871, 31, true);
            WriteLiteral("\',\r\n        FollowUpSurgical: \'");
            EndContext();
            BeginContext(8903, 29, false);
#line 246 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\eSyaOutPatient\Views\PatientClinicalForms\PatientForm.cshtml"
                      Write(Localizer["FollowUpSurgical"]);

#line default
#line hidden
            EndContext();
            BeginContext(8932, 29, true);
            WriteLiteral("\',\r\n     FollowUpNutrition: \'");
            EndContext();
            BeginContext(8962, 30, false);
#line 247 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\eSyaOutPatient\Views\PatientClinicalForms\PatientForm.cshtml"
                    Write(Localizer["FollowUpNutrition"]);

#line default
#line hidden
            EndContext();
            BeginContext(8992, 27, true);
            WriteLiteral("\',\r\n     TransactionDate: \'");
            EndContext();
            BeginContext(9020, 28, false);
#line 248 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\eSyaOutPatient\Views\PatientClinicalForms\PatientForm.cshtml"
                  Write(Localizer["TransactionDate"]);

#line default
#line hidden
            EndContext();
            BeginContext(9048, 23, true);
            WriteLiteral("\',\r\n     VisitNumber: \'");
            EndContext();
            BeginContext(9072, 24, false);
#line 249 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\eSyaOutPatient\Views\PatientClinicalForms\PatientForm.cshtml"
              Write(Localizer["VisitNumber"]);

#line default
#line hidden
            EndContext();
            BeginContext(9096, 20, true);
            WriteLiteral("\',\r\n     FormType: \'");
            EndContext();
            BeginContext(9117, 21, false);
#line 250 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\eSyaOutPatient\Views\PatientClinicalForms\PatientForm.cshtml"
           Write(Localizer["FormType"]);

#line default
#line hidden
            EndContext();
            BeginContext(9138, 19, true);
            WriteLiteral("\',\r\n     Actions: \'");
            EndContext();
            BeginContext(9158, 20, false);
#line 251 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\eSyaOutPatient\Views\PatientClinicalForms\PatientForm.cshtml"
          Write(Localizer["Actions"]);

#line default
#line hidden
            EndContext();
            BeginContext(9178, 25, true);
            WriteLiteral("\',\r\n          ViewForm: \'");
            EndContext();
            BeginContext(9204, 21, false);
#line 252 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\eSyaOutPatient\Views\PatientClinicalForms\PatientForm.cshtml"
                Write(Localizer["ViewForm"]);

#line default
#line hidden
            EndContext();
            BeginContext(9225, 28, true);
            WriteLiteral("\',\r\n        }\r\n</script>\r\n\r\n");
            EndContext();
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public IViewLocalizer Localizer { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<dynamic> Html { get; private set; }
    }
}
#pragma warning restore 1591
