#pragma checksum "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\eSyaMCServices\Views\SpecialtyUnits\V_1581_00.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "fb1eb07e67a43c2d6e606003237589e93a25dfe7"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.Areas_eSyaMCServices_Views_SpecialtyUnits_V_1581_00), @"mvc.1.0.view", @"/Areas/eSyaMCServices/Views/SpecialtyUnits/V_1581_00.cshtml")]
[assembly:global::Microsoft.AspNetCore.Mvc.Razor.Compilation.RazorViewAttribute(@"/Areas/eSyaMCServices/Views/SpecialtyUnits/V_1581_00.cshtml", typeof(AspNetCore.Areas_eSyaMCServices_Views_SpecialtyUnits_V_1581_00))]
namespace AspNetCore
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
#line 1 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\eSyaMCServices\Views\SpecialtyUnits\V_1581_00.cshtml"
using Microsoft.AspNetCore.Mvc.Localization;

#line default
#line hidden
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"fb1eb07e67a43c2d6e606003237589e93a25dfe7", @"/Areas/eSyaMCServices/Views/SpecialtyUnits/V_1581_00.cshtml")]
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"23ac09be4bcfaa7f9829a01d1a134874eaae1f3b", @"/Areas/eSyaMCServices/Views/_ViewImports.cshtml")]
    public class Areas_eSyaMCServices_Views_SpecialtyUnits_V_1581_00 : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<dynamic>
    {
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_0 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("src", new global::Microsoft.AspNetCore.Html.HtmlString("~/js/eSyaMCServices/SpecialtyUnits.js"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        #line hidden
        #pragma warning disable 0169
        private string __tagHelperStringValueBuffer;
        #pragma warning restore 0169
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext __tagHelperExecutionContext;
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner __tagHelperRunner = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner();
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __backed__tagHelperScopeManager = null;
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __tagHelperScopeManager
        {
            get
            {
                if (__backed__tagHelperScopeManager == null)
                {
                    __backed__tagHelperScopeManager = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager(StartTagHelperWritingScope, EndTagHelperWritingScope);
                }
                return __backed__tagHelperScopeManager;
            }
        }
        private global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper;
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            BeginContext(46, 2, true);
            WriteLiteral("\r\n");
            EndContext();
#line 4 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\eSyaMCServices\Views\SpecialtyUnits\V_1581_00.cshtml"
  
    ViewData["Title"] = "V_1581_00";
    Layout = "~/Views/Shared/_Layout.cshtml";

#line default
#line hidden
            DefineSection("scripts", async() => {
                BeginContext(191, 6, true);
                WriteLiteral("\r\n    ");
                EndContext();
                BeginContext(197, 61, false);
                __tagHelperExecutionContext = __tagHelperScopeManager.Begin("script", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "fb1eb07e67a43c2d6e606003237589e93a25dfe74207", async() => {
                }
                );
                __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper>();
                __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_0);
                await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
                if (!__tagHelperExecutionContext.Output.IsContentModified)
                {
                    await __tagHelperExecutionContext.SetOutputContentAsync();
                }
                Write(__tagHelperExecutionContext.Output);
                __tagHelperExecutionContext = __tagHelperScopeManager.End();
                EndContext();
                BeginContext(258, 2, true);
                WriteLiteral("\r\n");
                EndContext();
            }
            );
#line 11 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\eSyaMCServices\Views\SpecialtyUnits\V_1581_00.cshtml"
  
    var userFormRole = (eSyaEnterprise_UI.Models.DO_UserFormRole)ViewBag.UserFormRole;

#line default
#line hidden
            BeginContext(358, 46, true);
            WriteLiteral("<script>\r\n    var _userFormRole = JSON.parse(\'");
            EndContext();
            BeginContext(405, 38, false);
#line 15 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\eSyaMCServices\Views\SpecialtyUnits\V_1581_00.cshtml"
                               Write(Html.Raw(Json.Serialize(userFormRole)));

#line default
#line hidden
            EndContext();
            BeginContext(443, 52, true);
            WriteLiteral("\');\r\n\r\n     var localization = {\r\n         Active: \'");
            EndContext();
            BeginContext(496, 19, false);
#line 18 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\eSyaMCServices\Views\SpecialtyUnits\V_1581_00.cshtml"
             Write(Localizer["Active"]);

#line default
#line hidden
            EndContext();
            BeginContext(515, 23, true);
            WriteLiteral("\',\r\n         Actions: \'");
            EndContext();
            BeginContext(539, 20, false);
#line 19 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\eSyaMCServices\Views\SpecialtyUnits\V_1581_00.cshtml"
              Write(Localizer["Actions"]);

#line default
#line hidden
            EndContext();
            BeginContext(559, 20, true);
            WriteLiteral("\',\r\n         Edit: \'");
            EndContext();
            BeginContext(580, 17, false);
#line 20 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\eSyaMCServices\Views\SpecialtyUnits\V_1581_00.cshtml"
           Write(Localizer["Edit"]);

#line default
#line hidden
            EndContext();
            BeginContext(597, 20, true);
            WriteLiteral("\',\r\n         View: \'");
            EndContext();
            BeginContext(618, 17, false);
#line 21 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\eSyaMCServices\Views\SpecialtyUnits\V_1581_00.cshtml"
           Write(Localizer["View"]);

#line default
#line hidden
            EndContext();
            BeginContext(635, 22, true);
            WriteLiteral("\',\r\n         Update: \'");
            EndContext();
            BeginContext(658, 19, false);
#line 22 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\eSyaMCServices\Views\SpecialtyUnits\V_1581_00.cshtml"
             Write(Localizer["Update"]);

#line default
#line hidden
            EndContext();
            BeginContext(677, 233, true);
            WriteLiteral("\',\r\n    };\r\n\r\n</script>\r\n<section id=\"divGrid\">\r\n    <div class=\"row padbot10\">\r\n        <div class=\"col-lg-3\">\r\n            <div class=\"form-group\">\r\n                <label class=\"lable-color\"> Business Key</label>\r\n                ");
            EndContext();
            BeginContext(911, 51, false);
#line 31 "D:\eSya Project\Solution\eSyaEnterprise_UI\trunk\eSyaEnterprise_UI\Areas\eSyaMCServices\Views\SpecialtyUnits\V_1581_00.cshtml"
           Write(await Component.InvokeAsync("UserBusinessLocation"));

#line default
#line hidden
            EndContext();
            BeginContext(962, 4346, true);
            WriteLiteral(@"
            </div>
        </div>
        <div class=""col-lg-12 col-md-12 col-sm-12"">
            <table id=""jqgSpecialtyUnits""></table>
            <div id=""jqpSpecialtyUnits""></div>
        </div>
    </div>
</section>

<section id=""divForm"" style=""display:none"">

    <div class=""row"">
        <div class=""col-sm-12"" style=""display:none"">
            <div class=""form-group"">
                <label for=""txtSpecialtyId"">Specialty Id </label>
                <input class=""form-control"" type=""text"" id=""txtSpecialtyId"" />
            </div>
        </div>
        <div class=""col-sm-12"" style=""display:none"">
            <div class=""form-group"">
                <label for=""txtBusinesskey"">Business Key </label>
                <input class=""form-control"" type=""text"" id=""txtBusinesskey"" />
            </div>
        </div>

    </div>

    <div class=""row"">
        <div class=""col-lg-2 col-md-4 col-sm-6"">
            <div class=""form-group"">
                <label class=""lable-color"">N");
            WriteLiteral(@"o of Units</label>
                <input type=""text"" name=""name"" id=""txtNoofUnits"" value="""" class=""form-control integerFormat"" />
            </div>
        </div>
        <div class=""col-lg-2 col-md-4 col-sm-6"">
            <div class=""form-group"">
                <label class=""lable-color"">Effective From</label>
                <input type=""text"" name=""name"" id=""txtEffectiveFrom"" value="""" class=""datepicker form-control""  onkeydown=""event.preventDefault()""/>
            </div>
        </div>

        <div class=""col-lg-2 col-md-4 col-sm-6"">
            <div class=""form-group"">
                <label class=""lable-color"">New Patient</label>
                <input type=""text"" name=""name"" id=""txtNewPatient"" value="""" class=""form-control integerFormat"" />
            </div>
        </div>
        <div class=""col-lg-2 col-md-4 col-sm-6"">
            <div class=""form-group"">
                <label class=""lable-color"">Repeat Patient</label>
                <input type=""text"" name=""name"" id=""txtRe");
            WriteLiteral(@"peatPatient"" value="""" class=""form-control integerFormat"" />
            </div>
        </div>
        <div class=""col-lg-2 col-md-4 col-sm-6"">
            <div class=""form-group"">
                <label class=""lable-color"">No of Male Beds</label>
                <input type=""text"" name=""name"" id=""txtNoofMaleBeds"" value="""" class=""form-control integerFormat"" />
            </div>
        </div>
        <div class=""col-lg-2 col-md-4 col-sm-6"">
            <div class=""form-group"">
                <label class=""lable-color"">No of Female Beds</label>
                <input type=""text"" name=""name"" id=""txtNoofFemaleBeds"" value="""" class=""form-control integerFormat"" />
            </div>
        </div>
        <div class=""col-lg-2 col-md-4 col-sm-6"">
            <div class=""form-group"">
                <label class=""lable-color"">Common Beds</label>
                <input type=""text"" name=""name"" id=""txtCommonBeds"" value="""" class=""form-control integerFormat"" />
            </div>
        </div>
     ");
            WriteLiteral(@"   <div class=""col-lg-2 col-md-4 col-sm-6"">
            <div class=""form-group"">
                <label class=""lable-color"">Max Stay Allowed</label>
                <input type=""text"" name=""name"" value="""" id=""txtMaxStayAllowed"" class=""form-control integerFormat"" />
            </div>
        </div>

        <div class=""col-lg-2 col-md-4 col-sm-6"">
            <div class=""default-checkbox"">
                <label class=""mdl-checkbox mdl-js-checkbox mdl-js-ripple-effect"" for=""chkActiveStatus"">
                    <input type=""checkbox"" id=""chkActiveStatus"" class=""mdl-checkbox__input"">
                    <span class=""mdl-checkbox__label"">Active</span>
                </label>
            </div>
        </div>
        <div class=""col-lg-12 col-md-12 col-sm-12 text-center"">
            <hr />
            <button type=""button"" class=""mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent primary-button mr-10"" id=""fnSaveSpecialtyUnits"" onclick=""fnSaveSpecialtyUnits()""> ");
            WriteLiteral("Save</button>\r\n            <button type=\"button\" class=\"mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect  cancel-button\" id=\"btnCancel\" onclick=\"fnCloseSpecialtyUnits()\"> Cancel</button>\r\n\r\n        </div>\r\n    </div>\r\n</section>\r\n\r\n\r\n");
            EndContext();
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public IViewLocalizer Localizer { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<dynamic> Html { get; private set; }
    }
}
#pragma warning restore 1591
